- include_tasks: ping_check.yml
  when: IS_VNF == "false"

- shell: "sshpass -p {{VNFM_SYS_PASS_1}} ssh -o StrictHostKeyChecking=no {{VNFM_SYS_USER_1}}@{{VNFM_IP_1}} \"ping -c 2 -W 10 {{TEST_IP_ADDR}}\""
  register: ping_res
  when: IS_VNF == "true"

- shell: "{{STAT_CMD}}"
  register: status
  when: PING_RESULT == "OK"

- shell: "printf \"========================\n{{TEST_SETUP}}\n========================\n\" >> {{playbook_dir}}/../../../../LOGS/ping_status.log"
  when: not TEST_IP_ADDR == ""

- shell: "printf \"\nPING:\n{{TEST_IP_ADDR}} - {{PING_RESULT}}\" >> {{playbook_dir}}/../../../../LOGS/ping_status.log"
  when: not TEST_IP_ADDR == ""

- shell: "printf \"\n\nSTATUS:\n{{status.stdout}}\" >> {{playbook_dir}}/../../../../LOGS/ping_status.log"
  when: not TEST_IP_ADDR == ""

- shell: "printf \"\n\n\n\n\" >> {{playbook_dir}}/../../../../LOGS/ping_status.log"
  when: not TEST_IP_ADDR == ""
