---

- hosts: localhost
  vars_files:
    - ../../../vars/vnf_instantiation/urls.yml
    - ../../../vars/vnf_instantiation/ping_config.yml

  gather_facts: no

  tasks:
    - shell: "rm -rf {{playbook_dir}}/../../../../LOGS/ping_status.log"
      args:
        warn: false

    - include_tasks: get_stats.yml TEST_IP_ADDR="{{CMS_IP_1}}" TEST_SETUP="CMS ACTIVE" STAT_CMD="sshpass -p {{CMS_SYS_PASS_1}} ssh -o StrictHostKeyChecking=no {{CMS_SYS_USER_1}}@{{CMS_IP_1}} service cms status" IS_VNF="false"
      when: not CMS_IP_1 == ""

    - include_tasks: get_stats.yml TEST_IP_ADDR="{{CMS_IP_2}}" TEST_SETUP="CMS STANDBY" STAT_CMD="sshpass -p {{CMS_SYS_PASS_2}} ssh -o StrictHostKeyChecking=no {{CMS_SYS_USER_2}}@{{CMS_IP_2}} service cms status" IS_VNF="false"
      when: not CMS_IP_1 == ""

    - include_tasks: get_stats.yml TEST_IP_ADDR="{{VNFM_IP_1}}" TEST_SETUP="VNFM 1" STAT_CMD="sshpass -p {{VNFM_SYS_PASS_1}} ssh -o StrictHostKeyChecking=no {{VNFM_SYS_USER_1}}@{{VNFM_IP_1}} service vnfm status" IS_VNF="false"
      when: not VNFM_IP_1 == ""

    - include_tasks: get_stats.yml TEST_IP_ADDR="{{VNFM_IP_2}}" TEST_SETUP="VNFM 2" STAT_CMD="sshpass -p {{VNFM_SYS_PASS_2}} ssh -o StrictHostKeyChecking=no {{VNFM_SYS_USER_2}}@{{VNFM_IP_2}} service vnfm status" IS_VNF="false"
      when: not VNFM_IP_2 == ""

    - include_tasks: get_stats.yml TEST_IP_ADDR="{{item.value}}" TEST_SETUP="{{item.key}}" STAT_CMD="sshpass -p {{VNFM_SYS_PASS_1}} ssh -o StrictHostKeyChecking=no {{VNFM_SYS_USER_1}}@{{VNFM_IP_1}} \"rm -rf ~/.ssh/known_hosts && sshpass -p mavenir ssh -o StrictHostKeyChecking=no root@{{item.value}} 'ldconfig && /usr/IMS/current/bin/readShm' \"" IS_VNF="true"
      with_dict: "{{VNF_IPS}}"
      ignore_errors: yes
