- name: "Ping the server"
  shell: "ping -c 2 -W 10 {{TEST_IP_ADDR}}"
  ignore_errors: yes
  register: ping_res

- set_fact:
    PING_RESULT: "FAIL"
  when: ping_res.failed

- set_fact:
    PING_RESULT: "OK"
  when: not ping_res.failed
