- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  delegate_to: localhost
  register: login_response

- set_fact:
    FLAVOR_NAME: []
  when: not FLAVOR_NAME is defined
  
- shell: "curl -k --data 'listName=volume_flavor&rowData={\"flavorName\":\"{{F_NAME}}\",\"description\":\"{{FLAVOR_DESCRIPTION[F_INDEX]}}\",\"volumeSize\":{{FLAVOR_VOLUME_SIZE[F_INDEX]}}}' --cookie '{{login_response.set_cookie}}' {{Provider_Add_URL}}"
  delegate_to: localhost
  loop: "{{FLAVOR_NAME}}"
  loop_control:
    loop_var: F_NAME
    index_var: F_INDEX
