
---

  - name: "Get VNFD*.xml from Descriptor folder"
    find:
      paths: "{{  DESCRIPTOR_PATH }}{{ item }}/"
      patterns: "*VNFD*.xml"
    with_items:
      "{{ DESCRIPTOR_INFO }}"
    register: FIND_RES
    delegate_to: localhost

  - name: "Get all VNFD file paths in an array"
    set_fact:
      VNFD_FILES: "{{ VNFD_FILES|default([]) + [ item[1].path ] }}"
    with_subelements:
    - "{{ FIND_RES.results }}"
    - files
    delegate_to: localhost

  - name: "Get matches for id(vdu id) from xml"
    xml:
      xmlstring: "{{lookup('file', '{{item}}') | regex_replace('xmlns=.*>', '>')}}"
      xpath: /vnfd/vnfd-list/vdu/id
      content: text
    with_items:
      "{{VNFD_FILES}}"
    register: xmlresp
    delegate_to: localhost

  - name: "Get VDU IDs from xmlresp"
    set_fact:
      VDU_IDS: "{{ VDU_IDS|default([]) + [ {'vduid':item.matches.0.id, 'file_path':item.item} ] }}"
    with_items:
      "{{ xmlresp.results }}"

  - name: "Get matches for VNFD Version from xml"
    xml:
      xmlstring: "{{lookup('file', '{{item}}') | regex_replace('xmlns=.*>', '>')}}"
      xpath: /vnfd/vnfd-list/descriptor-version
      content: text
    with_items:
      "{{VNFD_FILES}}"
    register: xmlresp
    delegate_to: localhost

  - name: "Get VNFD Versions from xmlresp"
    set_fact:
      VNFD_VERSIONS: "{{ VNFD_VERSIONS|default([]) + [ item['matches'][0]['descriptor-version'] ] }}"
    with_items:
      "{{ xmlresp.results }}"

  - name: "Get matches for VNFD-ID from xml"
    xml:
      xmlstring: "{{lookup('file', '{{item}}') | regex_replace('xmlns=.*>', '>')}}"
      xpath: /vnfd/vnfd-list/vnfd-id
      content: text
    with_items:
      "{{VNFD_FILES}}"
    register: xmlresp
    delegate_to: localhost

  - name: "Get VNFD-IDs from xmlresp"
    set_fact:
      VNFD_IDS: "{{ VNFD_IDS|default([]) + [ item['matches'][0]['vnfd-id'] ] }}"
    with_items:
      "{{ xmlresp.results }}"

  - include_tasks: ./ConfigData_Add_Included_Tasks.yml item={{item}}
    with_together:
      - "{{ VDU_IDS }}"
      - "{{ VNFD_VERSIONS }}"
      - "{{ VNFD_IDS }}"
