---
#
# - hosts: localhost
#   vars_files:
#     - ../vars/Config.yml
#     - ../vars/urls.yml
#     - ../vars/Descriptor_ConfigFile_Yang.yml
  - set_fact:
      CONFIGMODEL_ADD_VNFD_PATHS: []
  # tasks:


  - include_tasks: ./query_db.yml QUERY="select version from cms_version"
  - set_fact: CMS_Version={{RESP.stdout_lines.0}}
    when: RESP.stdout_lines.0 is defined

  - include_tasks : ./ConfigModel/List_ConfigModel_folder.yml
                        PATH="{{ DESCRIPTOR_PATH }}/{{ item }}/"
    with_items: "{{ DESCRIPTOR_INFO }}"

  - name: loop over result
    debug:
      msg="{{item}}"
    with_items: "{{CONFIGMODEL_ADD_VNFD_PATHS}}"

  - include_tasks : ./ConfigModel/ConfigModel_Delete_tasks.yml
                        XML_PATH="{{xml_file}}"

    with_items: "{{ CONFIGMODEL_ADD_VNFD_PATHS }}"
    loop_control:
        loop_var: xml_file
