- include_tasks: ./query_db.yml QUERY="select vnf_data_config.id from vnf_data_config INNER JOIN data_model ON vnf_data_config.fk_data_model=data_model.id where data_model.nsd_id=(select id from nsd_descriptor where version='{{NSD_VERSION}}' AND name='{{NSD_Name}}' )"
- set_fact: DEL_IDS="{{RESP.stdout_lines}}"

- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost
  
- shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{IMPORT_SNAPSHOT_CONFIG_URL}}/null/{{item}}"
  delegate_to: localhost
  with_items: "{{DEL_IDS}}"
  register: curl_resp
