- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  delegate_to: localhost
  register: login_response
- set_fact:
    QUERY_BUILDER: ""

- set_fact:
    QUERY_BUILDER: "{{QUERY_BUILDER}} OR (flavorName='{{F_NAME}}')"
  loop: "{{FLAVOR_NAME}}"
  loop_control:
    loop_var: F_NAME
    index_var: F_INDEX
  when: FLAVOR_NAME is defined

- include_tasks: query_db.yml QUERY="select id from volume_flavor where {{QUERY_BUILDER[3:]}}"
  when: FLAVOR_NAME is defined

- set_fact:
    DB_IDS: "{{RESP.stdout_lines}}"
  when: FLAVOR_NAME is defined

- set_fact:
    DB_IDS: []
  when: not FLAVOR_NAME is defined

- shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{CMS_URL}}/cms-service/webapi/data/volume_flavor/null/{{F_ID}}"
  delegate_to: localhost
  loop: "{{DB_IDS}}"
  loop_control:
    loop_var: F_ID
  when: FLAVOR_NAME is defined
