---

- hosts: cms
  vars_files:
    - ../../vars/vnf_instantiation/urls.yml
    - ../../vars/vnf_instantiation/config.yml
    - ../../vars/vnf_instantiation/Descriptor_ConfigFile_Yang.yml
  gather_facts: no

  tasks:

    - include_tasks: setup_pwdless_login.yml
    #- include_tasks: add_cms_flavor.yml
    #- include_tasks: Image_save.yml
    #- include_tasks: Image_onboard.yml
    - include_tasks: Descriptor_Save_Quick.yml
    - include_tasks: Descriptor_Onboard_Quick.yml
    - include_tasks: ConfigModel_Add_Quick.yml
    - include_tasks: ConfigData_Add_Quick.yml
    - include_tasks: OfflineConfig_Add_Quick.yml
    #- include_tasks: Deploy_NSD_Quick.yml
