---


- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- name: Send HTTP {{ METHOD }}

  uri:
      url:          "{{ URL }}"
      method:       "{{ METHOD }}"
      body:         "{{ PAYLOAD }}"
      status_code:  200
      headers:
        Content-Type: application/x-www-form-urlencoded
        Cookie: "{{login_response.set_cookie}}"
      validate_certs: no

  register: http_resp
  delegate_to: localhost

- debug:
    msg: "{{ PAYLOAD }}"

- debug:
    msg: "{{http_resp}}"
