- include_tasks: query_db.yml QUERY="SELECT id FROM cloud_tenant_config WHERE name='{{ Tenant_Name}}'"
- set_fact: Tenant_id={{ RESP.stdout_lines.0 }}

- include_tasks: query_db.yml QUERY="SELECT id FROM image_config  WHERE name='{{ item.name }}'"
- set_fact: Image_Id={{ RESP.stdout_lines.0 }}

- set_fact: ImageName={{ item.name }}
- set_fact: ImagePath={{ item.path }}

- include_tasks: ./https_request_no_template_quick.yml
                      URL="{{ Image_Onboard_URL }}"
                      METHOD="POST"
                      PAYLOAD="listName=image_config&rowData={'lastUpdated':'','cloudProfileID':'{{ Cloud_Type}}-{{ POP_IP }}-{{ Tenant }}-{{ Tenant_User_Name }}','imageName':'{{ ImageName }}','imageId':'','cloudType':'{{ Cloud_Type }}','tenantID':'{{ Tenant_id }}','imageFilePath':'{{ ImagePath }}','id':'{{ Image_Id }}','imageType':'IMAGE','status':'SAVED'}"

- include_tasks: query_db.yml QUERY="SELECT id FROM image_config  WHERE name='{{ ImageName }}'"

- set_fact:
    Image_Id: "{{ RESP.stdout_lines.0 }}"

# - command: "mysql -u{{ MYSQL_USER }} -p{{ MYSQL_PASSWD }} {{ MYSQL_DB }} -sN -e \"SELECT status FROM image_config_status  WHERE fk_image_config='{{Image_Id}}'\" "
#   register: STATUS_RESP
#   remote_user: "{{CMS_IP_SYSUSER}}"
#   retries: "{{DESCRIPTOR_RETRIES}}"
#   delay: "{{ DELAY }}"
#   until: ( STATUS_RESP.stdout_lines.0|lower in "Uploaded"|lower) or (STATUS_RESP.stdout_lines.0|lower in "Failed"|lower)
#   ignore_errors: yes
#
# - debug:
#     msg:
#     - ""
#     - ""
#     - "################################################################"
#     - "################################################################"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###             IMAGE WAS UPLOADED SUCCESSFULLY!!!           ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "################################################################"
#     - "################################################################"
#     - ""
#     - ""
#   when: ( STATUS_RESP.stdout_lines.0|lower in "Uploaded"|lower)
#
# - fail:
#     msg:
#     - ""
#     - ""
#     - "################################################################"
#     - "################################################################"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###                   IMAGE UPLOAD FAILED                    ###"
#     - "###  PLEASE CHECK THE LOGS, RESOLVE THE ISSUE AND TRY AGAIN  ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "###                                                          ###"
#     - "################################################################"
#     - "################################################################"
#     - ""
#     - ""
#   when: not ( STATUS_RESP.stdout_lines.0|lower in "Uploaded"|lower)
