---

- name: List Snapshots
  include_tasks: query_db.yml
  vars:
      QUERY: "select id, name from vnf_data_config where name like '%Snapshot%'"


- pause:
    prompt: "ID\tNAME\n{{RESP.stdout}}\n\nChoose config id you want to download"
  register: config_id

- include_tasks: query_db.yml
  vars:
      QUERY: "select name from vnf_data_config where id='{{config_id.user_input}}'"

- set_fact:
    SNAPSHOT_ID: "{{config_id.user_input}}"
    SNAPSHOT_NAME: "{{RESP.stdout_lines.0}}"

- include_tasks: query_db.yml
  vars:
      QUERY: "select xml_data from vnf_global_config_snapshot where fk_vnf_data_config='{{SNAPSHOT_ID}}'"

- set_fact:
    XML_CONTENT: "{{RESP.stdout}}"

- copy: content="{{XML_CONTENT|replace('\\n','\n')|replace('\\t','\t')| trim}}" dest="{{playbook_dir}}/../../files/vnf_instantiation/CONFIG_DOWNLOADS/{{SNAPSHOT_NAME}}.xml"
  delegate_to: localhost

- shell: "python {{playbook_dir}}/../../files/vnf_instantiation/xl_xml.py {{playbook_dir}}/../../files/vnf_instantiation/CONFIG_DOWNLOADS/{{SNAPSHOT_NAME}}.xml"
  delegate_to: localhost

- shell: "rm -rf {{playbook_dir}}/../../files/vnf_instantiation/CONFIG_DOWNLOADS/{{SNAPSHOT_NAME}}.xml"
  delegate_to: localhost

- pause:
    prompt: "FILE {{SNAPSHOT_NAME}}.xlsx\nsaved in {{playbook_dir}}/../../files/vnf_instantiation/CONFIG_DOWNLOADS/\nAfter modifying excel file Press Enter to apply snapshot"

- include_tasks: Apply_Snapshot.yml
