---

# - hosts: localhost
#   vars_files:
#     - ../vars/Config.yml
#     - ../vars/urls.yml
#     - ../vars/Descriptor_ConfigFile_Yang.yml
  - set_fact:
      OFFLINECONFIG_ADD_VNFD_PATHS: []
      OFFLINECONFIG_ADD_CONFIG_PATHS: []
  # tasks:
  - include_tasks: query_db.yml QUERY="select version from cms_version"
  - set_fact: CMS_Version={{RESP.stdout_lines.0}}
    when: RESP.stdout_lines.0 is defined

  - include_tasks : ./OfflineConfig/List_OfflineConfig_folder.yml
    vars:
        PATH: "{{ DESCRIPTOR_PATH }}/{{ item }}/"
    with_items: "{{ DESCRIPTOR_INFO }}"

  - name: loop over result
    debug:
      msg="{{item}}"
    with_items: "{{OFFLINECONFIG_ADD_VNFD_PATHS}}"




  - include_tasks : ./OfflineConfig/List_OfflineConfig_Config_folder.yml
    vars:
        PATH: "{{ DESCRIPTOR_PATH }}/{{ item }}/Config/"
    with_items: "{{ DESCRIPTOR_INFO }}"

  - name: looop over result
    debug:
      msg="{{item}}"
    with_items: "{{OFFLINECONFIG_ADD_CONFIG_PATHS}}"




  - include_tasks : ./OfflineConfig/OfflineConfig_Delete_tasks.yml
    vars:
        XML_PATH: "{{xml_file}}"

    with_items: "{{ OFFLINECONFIG_ADD_VNFD_PATHS }}"
    loop_control:
        loop_var: xml_file
