---

- hosts: cms
  vars_files:
    - ../../vars/vnf_instantiation/urls.yml
    #- ../vars/config.yml
    # - ../../vars/vnf_instantiation/online_config.yml
    - ../../vars/vnf_instantiation/config.yml
    - ../../vars/vnf_instantiation/Descriptor_ConfigFile_Yang.yml
  gather_facts: no

  tasks:
    - include_tasks: setup_pwdless_login.yml
    - include_tasks: List_Snapshots.yml
