---

- hosts: cms
  vars_files:
    - ../../vars/vnf_instantiation/urls.yml
    #- ../vars/config.yml
    # - ../../vars/vnf_instantiation/online_config.yml
    - ../../vars/vnf_instantiation/config.yml
    - ../../vars/vnf_instantiation/Descriptor_ConfigFile_Yang.yml
  gather_facts: no

  tasks:
    - name: List Snapshots
      include_tasks: query_db.yml
      vars:
          QUERY: "select id, name from vnf_data_config where name like '%Snapshot%'"


    - pause:
        prompt: "ID\tNAME\n{{RESP.stdout}}\n\nChoose config id you want to rollback to"
      register: config_id

    - include_tasks: query_db.yml
      vars:
          QUERY: "select name from vnf_data_config where id='{{config_id.user_input}}'"

    - set_fact:
        SNAPSHOT_ID: "{{config_id.user_input}}"
        SNAPSHOT_NAME: "{{RESP.stdout_lines.0}}"

    - include_tasks: query_db.yml
      vars:
          QUERY: "select fk_data_model from vnf_data_config where id='{{SNAPSHOT_ID}}'"

    - set_fact:
        FK_DATA_MODEL: "{{RESP.stdout_lines.0}}"

    - include_tasks: query_db.yml
      vars:
          QUERY: "select vdu_id from vnf_config where fk_data_model='{{FK_DATA_MODEL}}'"

    - set_fact:
        VDU_ID: "{{RESP.stdout_lines.0}}"

    - set_fact:
        CONFIGURED_ID: "{{SNAPSHOT_ID}}"

    - include_tasks: query_db.yml
      vars:
          QUERY: "select fk_vnf_data_running_version from vnf_config_status where vdu_id='{{VDU_ID}}'"

    - set_fact:
        RUNNING_ID: "{{RESP.stdout_lines.0}}"

    - include_tasks: query_db.yml
      vars:
          QUERY: "select name from vnf_data_config where id={{RUNNING_ID}}"
      when: not RUNNING_ID == "NULL"

    - set_fact:
        RUNNING_NAME: "{{RESP.stdout_lines.0}}"
      when: not RUNNING_ID == "NULL"

    - set_fact:
        RUNNING_NAME: ""
      when: RUNNING_ID == "NULL"

    - set_fact:
        RESOURCE_ID: "{{ GIVEN_NAME| to_uuid }}"
        CONFIGURED_NAME: "Snapshot-{{GIVEN_NAME}}"

    - include_tasks: query_db.yml
      vars:
          QUERY: "select id from vnf_config_status where vdu_id='{{VDU_ID}}'"
    - set_fact:
        VNF_CONFIG_STATUS_ID: "{{RESP.stdout_lines.0}}"

    - shell: "curl -s  -k -X  POST -F rowData=\"{'id':'{{VNF_CONFIG_STATUS_ID}}', 'vnf':'{{VDU_ID}}', configuredId: '{{CONFIGURED_ID}}', configuredName: '{{CONFIGURED_NAME}}', 'runningId': '{{RUNNING_ID}}', 'runningName': '{{RUNNING_NAME}}', 'resourceId':'{{RESOURCE_ID}}', 'haOperMode':'active_c'}\" --cookie '{{login_response.set_cookie}}' {{APPLY_SNAPSHOT_URL}}"
      register: curl_resp
      args:
        warn: false
      delegate_to: localhost

    - debug: msg="{{curl_resp}}"
