---

- include_tasks: query_db.yml QUERY="SELECT id FROM cloud_tenant_config WHERE name='{{Tenant_Name}}'"

- set_fact:
    Tenent_id: "{{ RESP.stdout_lines.0 }}"

- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{ Tenant_Delete_URL }}/{{ Tenent_id }}"
  delegate_to: localhost
  register: curl_resp
