---

- name: Add New VNFM1
  include_tasks: https_request.yml
  vars:
      METHOD:   POST
      URL:      "{{ VNFM_Add_URL }}"
      PAYLOAD:  "VNFM.j2"

- name: Add New VNFM2
  include_tasks: https_request.yml
  vars:
      METHOD:   POST
      URL:      "{{ VNFM_Add_URL }}"
      PAYLOAD:  "VNFM2.j2"
