---

- include_tasks: query_db.yml QUERY="SELECT id FROM vnfm_config WHERE name='{{ VNFM1_Name}}'"

# - name: Delete VNFM {{ VNFM1_Name}}
#   include_tasks: https_requestuest.yml
#   vars:
#     METHOD:     DELETE
#     URL:        "{{ VNFM_Delete_URL }}/{{ RESP.stdout_lines.0 }}"
#     PAYLOAD:    "VNFM.j2"
#
#   when:  RESP.stdout_lines



- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{ VNFM_Delete_URL }}/{{ RESP.stdout_lines.0 }}"
  delegate_to: localhost
  register: curl_resp

- include_tasks: query_db.yml QUERY="SELECT id FROM vnfm_config WHERE name='{{ VNFM2_Name}}'"

- shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{ VNFM_Delete_URL }}/{{ RESP.stdout_lines.0 }}"
  delegate_to: localhost
  register: curl_resp
