- name: print the date
  hosts: all
  tasks: 

- name: create array reversed
  set_fact: output_count=[]

- shell: "ls"
  args: 
  chdir: "/tmp"
  register: output 
- debug: var=output.stdout_lines

- shell: "cp {{ item }} {{item}}_bkp"
  with_items:
    - "{{ output.stdout_lines }}"

  register: output 
    - debug: var=output.stdout_lines





    - name: Set output_count fact
      set_fact: output_count=output.stdout_lines
    - debug: var=output_count

