---
- hosts: localhost
  vars:
    tasks:
      - name: new variable with current date time
        set_fact: date="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"
      - name: print variable
        debug: msg="Current date and time is {{date}}"

      - hosts: all
        vars:
          #    temp="{{ hostvars['localhost']['date'] }}"
          tasks:
            - name: print variable
              debug: msg="{{ hostvars['localhost']['date'] }}"
              #      debug: msg="Current date and time is {{temp}}"

