
---

   - block:
      - include: "{{role_path}}/../common/tasks/upload_glance_image.yaml"
        when:  UPLOAD_GLANCE_IMAGE

#      - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/files/heat_templates/{{ item }} local_dir={{ HOST_TEMP_STORAGE }}"
#        with_flattened: "{{ transfer_file_list }}"

      - include: "{{role_path}}/../common/tasks/create_heat_stack.yaml heat_tmpl_file={{item.0}} heat_env_file={{item.1}}"
        with_together:
             - "{{ HEAT_TEMPLATE_FILENAME_LIST }}"
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ CREATE_STACK_LIST }}"
        when: "{{item.2}}"


      - include: "{{role_path}}/../common/tasks/delete_heat_stack.yaml heat_tmpl_file={{item.0}} heat_env_file={{item.1}}"
        with_together:
             - "{{ HEAT_TEMPLATE_FILENAME_LIST }}"
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ DELETE_STACK_LIST }}"
        when: "{{item.2}}"

      - include: "{{role_path}}/../common/tasks/delete_glance_image.yaml"
        when:  DELETE_GLANCE_IMAGE

      - include: "{{role_path}}/../common/tasks/print_stack_status.yaml  heat_env_file={{item.0}}"
        with_together:
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ CREATE_STACK_LIST }}"
        when: "{{item.1}}"

     rescue:
      - include: "{{role_path}}/../common/tasks/print_stack_status.yaml  heat_env_file={{item.0}}"
        with_together:
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ CREATE_STACK_LIST }}"
        when: "{{item.1}}"

      - include: "{{role_path}}/../common/tasks/delete_heat_stack.yaml heat_tmpl_file={{item.0}} heat_env_file={{item.1}}"
        with_together:
             - "{{ HEAT_TEMPLATE_FILENAME_LIST }}"
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ DELETE_STACK_LIST }}"
        when: "{{item.2}} and rollback_on_failure"

      - include: "{{role_path}}/../common/tasks/delete_glance_image.yaml"
        when: "{{ DELETE_GLANCE_IMAGE }} and rollback_on_failure "

     always:

      - include: "{{role_path}}/../common/tasks/print_stack_status.yaml  heat_env_file={{item.1}}"
        with_together:
             - "{{ HEAT_TEMPLATE_FILENAME_LIST }}"
             - "{{ HEAT_TEMPLATE_ENV_FILENAME_LIST }}"
             - "{{ STACK_STATUS_LIST }}"
        when: "{{item.2}}"

