---

- hosts: cms
  
  vars_files:
    - ../vars/urls.yml

  gather_facts: no

  tasks:

#    - include_tasks:  ./setup_pwdless_login.yml

    - include_tasks: ../tasks/https_request.yml
      vars:
          URL: "{{BACKUP_URL}}"
          METHOD: "POST"
          PAYLOAD: "{{BK_TEMPLATE}}" 
