---

- hosts: cms

  vars_files:
    - ../vars/urls.yml

  gather_facts: no

  tasks:

#    - include_tasks:  ./setup_pwdless_login.yml

    - include_tasks: ../tasks/https_get_request.yml
      vars:
          URL: "https://{{inventory_hostname}}:18080/cms-service/webapi/cmsManageService/getData/system_backup_file"
          METHOD: "GET"

    - debug:
         msg: "ID::( {{item.id}} ) belongs to backupFilePath::( {{item.backupFilePath}} )"
      with_items: "{{http_resp.json.context.entity}}"
    
- hosts: cms
  
  vars_files:
    - ../vars/urls.yml

  gather_facts: no

  tasks:  

    - pause:
        prompt: "Location of server?  Input options: are in above debug message "
      register: config_id

    - set_fact:
        IDs: "{{config_id.user_input}}"

    - include_tasks: ../tasks/https_request.yml ID={{vars.IDs}}
      vars:
          URL: "{{BACKUP_URL}}"
          METHOD: "POST"
          PAYLOAD: "{{BK_TEMPLATE}}" 
