- set_fact:
    SSH_IP: "{{OAM_CONF[inventory_hostname]['OAM_IP']}}"

- name: "Copy host_config.xml from {{playbook_dir}}/../../files/dell_os_installation/host_config.xml in localhost to {{HOME_DIR}} in the remote host"
  copy:
    src: "{{playbook_dir}}/../../files/dell_os_installation/host_config.xml"
    dest: "{{HOME_DIR}}"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"


- name: "Run host-bulk-add with the host_config file"
  shell: "source {{KEYSTONE_SOURCE_FILE_PATH}} && system host-bulk-add {{HOME_DIR}}/host_config.xml"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"
  ignore_errors: yes
