- set_fact:
    SSH_IP: "{{OAM_CONF[inventory_hostname]['OAM_IP']}}"
    DEVICE_FILE: "/etc/sysconfig/network-scripts/ifcfg-{{OAM_CONF[inventory_hostname]['OAM_DEVICE']}}"
    OAM_DEVICE: "{{OAM_CONF[inventory_hostname]['OAM_DEVICE']}}"
    OAM_IP: "{{OAM_CONF[inventory_hostname]['OAM_IP']}}"
    NETMASK: "{{OAM_CONF[inventory_hostname]['NETMASK']}}"
    GATEWAY: "{{OAM_CONF[inventory_hostname]['GATEWAY']}}"
    DNS1: "{{OAM_CONF[inventory_hostname]['DNS1']}}"
    DNS2: "{{OAM_CONF[inventory_hostname]['DNS2']}}"
    VNC_CMD: "vncdotool -s {{inventory_hostname}}::{{VNC_PORT}} -p {{VNC_PASSWORD}}"

- name: Wait for login prompt and change windriver password
  shell: "{{VNC_CMD}} key enter sleep 5 expect {{playbook_dir}}/../../files/dell_os_installation/automation_support_images/login_username.png 0 type {{WRUSER}} pause 2 key enter expect {{playbook_dir}}/../../files/dell_os_installation/automation_support_images/login_password.png 0 type {{WR_DFLT_PASS}} pause 2 key enter pause 5 type {{WR_DFLT_PASS}} pause 2 key enter pause 5 type {{WRPASS}} pause 2 key enter pause 5 type {{WRPASS}} pause 2 key enter"
  delegate_to: localhost

- name: Open up OAM config
  shell: "{{VNC_CMD}} type 'sudo -i' key enter pause 5 type {{WRPASS}} key enter pause 5 type 'vi /etc/sysconfig/network-scripts/ifcfg-{{OAM_DEVICE}}' pause 5 key enter"
  delegate_to: localhost

- name: Update OAM Device config
  shell: "{{VNC_CMD}} type 'd0d1000dd' sleep 2 key i key i key i sleep 2 type 'ONBOOT=yes' sleep 2 key enter sleep 2 type 'IPADDR={{OAM_IP}}' sleep 2 key enter sleep 2 type 'GATEWAY={{GATEWAY}}' sleep 2 key enter sleep 2 type 'NETMASK={{NETMASK}}' sleep 2 key enter sleep 2 type 'DEVICE={{OAM_DEVICE}}' sleep 2 key enter sleep 2 key esc sleep 2 key : key w sleep 2 key q sleep 2 key enter"
  delegate_to: localhost

- name: Restart Network
  shell: "{{VNC_CMD}} type '/etc/init.d/network restart' sleep 2 key enter"
  delegate_to: localhost
