- set_fact:
    SSH_IP: "{{OAM_ADDR[inventory_hostname]}}"

- apt:
    name: python-pip
    state: present
  delegate_to: localhost
  # remote_user: "{{WRUSER}}"
  # become: yes
  # become_method: sudo
  # become_user: "{{WR_SUDO_USER}}"

- pip:
    name: passlib
  delegate_to: localhost
  # remote_user: "{{WRUSER}}"
  # become: yes
  # become_method: sudo
  # become_user: "{{WR_SUDO_USER}}"

- shell: "python -c \"from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt('{{WRPASS}}')\""
  register: pass_hash
  delegate_to: localhost

- name: "Change {{WRUSER}} password"
  user: name={{WRUSER}} update_password=always password="{{pass_hash.stdout_lines.0}}"
  remote_user: "{{WRUSER}}"
  become: yes
  become_method: sudo
  become_user: "{{WR_SUDO_USER}}"
  delegate_to: "{{SSH_IP}}"
  ignore_errors: yes
