- set_fact:
    SSH_IP: "{{OAM_CONF[inventory_hostname]['OAM_IP']}}"

- shell: "rm -rf {{HOME_DIR}}/license.lic"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"
  args:
    warn: False

- shell: "rm -rf {{HOME_DIR}}/Patches"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"
  args:
    warn: False

- shell: "mkdir {{HOME_DIR}}/Patches"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"
  args:
    warn: False

- name: "Copy License from {{LICENSE_SOURCE_PATH}} in localhost to {{HOME_DIR}} in the remote host"
  copy:
    src: "{{LICENSE_SOURCE_PATH}}"
    dest: "{{HOME_DIR}}"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"

- name: "Copy Patch folder from {{PATCH_SOURCE_PATH}} in localhost to {{HOME_DIR}} in the remote host"
  copy:
    src: "{{PATCH_SOURCE_PATH}}/"
    dest: "{{HOME_DIR}}/Patches/"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"

- name: "Copy 'screen.rpm' in {{playbook_dir}}/../../files/dell_os_installation/"
  copy:
    src: "{{playbook_dir}}/../../files/dell_os_installation/screen.rpm"
    dest: "{{HOME_DIR}}"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"

- name: "Install screen"
  shell: "yum -y install {{HOME_DIR}}/screen.rpm"
  args:
    warn: False
  remote_user: "{{WRUSER}}"
  become: yes
  become_user: "{{WR_SUDO_USER}}"
  become_method: sudo
  delegate_to: "{{SSH_IP}}"
  ignore_errors: yes

- name: "Copy Controller_config.cfg from {{playbook_dir}}/../../files/dell_os_installation/controller_config.cfg in localhost to {{HOME_DIR}} in the remote host"
  copy:
    src: "{{playbook_dir}}/../../files/dell_os_installation/controller_config.cfg"
    dest: "{{HOME_DIR}}"
  remote_user: "{{WRUSER}}"
  delegate_to: "{{SSH_IP}}"

- shell: "echo 'yum -y install {{HOME_DIR}}/screen.rpm' >> /etc/rc.d/rc.local"
  remote_user: "{{WRUSER}}"
  become: yes
  become_user: "{{WR_SUDO_USER}}"
  become_method: sudo
  delegate_to : "{{SSH_IP}}"

- shell: "echo 'sudo screen -dmS controller_config bash -c \"cd {{HOME_DIR}} && config_controller --config-file controller_config.cfg  && {{HOME_DIR}}/bring_oam_up.sh && head -n -2 /etc/rc.d/rc.local > /etc/rc.d/rc.local.tmp && rm -rf /etc/rc.d/rc.local && mv /etc/rc.d/rc.local.tmp /etc/rc.d/rc.local && reboot; exec bash\"' >> /etc/rc.d/rc.local"
  remote_user: "{{WRUSER}}"
  become: yes
  become_user: "{{WR_SUDO_USER}}"
  become_method: sudo
  delegate_to: "{{SSH_IP}}"

#- shell: "echo 'head -n -3 /etc/rc.d/rc.local > /etc/rc.d/rc.local.tmp ; rm -rf /etc/rc.d/rc.local;  mv /etc/rc.d/rc.local.tmp /etc/rc.d/rc.local;' >> /etc/rc.d/rc.local"
#  remote_user: "{{WRUSER}}"
#  become: yes
#  become_user: "{{WR_SUDO_USER}}"
#  become_method: sudo
#  delegate_to: "{{SSH_IP}}"

- shell: "chmod +x /etc/rc.d/rc.local"
  remote_user: "{{WRUSER}}"
  become: yes
  become_user: "{{WR_SUDO_USER}}"
  become_method: sudo
  delegate_to: "{{SSH_IP}}"
  args:
    warn: False

- name: "Starting a screen session with name 'install_patches' to upload, apply and install patches"
  shell: "screen -dmS install_patches bash -c 'sw-patch upload {{HOME_DIR}}/Patches/* && sw-patch apply --all && sw-patch install-local && {{HOME_DIR}}/bring_oam_up.sh && reboot; exec bash'"
  remote_user: "{{WRUSER}}"
  become: yes
  become_user: "{{WR_SUDO_USER}}"
  become_method: sudo
  delegate_to: "{{SSH_IP}}"

# - name: "Upload Patch"
#   shell: "sw-patch upload {{HOME_DIR}}/Patches/*"
#   remote_user: "{{WRUSER}}"
#   become: yes
#   become_user: "{{WR_SUDO_USER}}"
#   become_method: sudo
#   delegate_to: "{{SSH_IP}}"
#
# - name: "Apply Patch"
#   shell: "sw-patch apply -–all"
#   remote_user: "{{WRUSER}}"
#   become: yes
#   become_user: "{{WR_SUDO_USER}}"
#   become_method: sudo
#   delegate_to: "{{SSH_IP}}"
#   ignore_errors: yes
#
# - name: "Install Local"
#   shell: "sw-patch install-local"
#   remote_user: "{{WRUSER}}"
#   become: yes
#   become_user: "{{WR_SUDO_USER}}"
#   become_method: sudo
#   delegate_to: "{{SSH_IP}}"
