---

- hosts: idrac
  gather_facts: no
  vars_files:
    - ../../vars/dell_os_installation/config.yml
    - ../../vars/dell_os_installation/oam_conf.yml
    - ../../vars/dell_os_installation/network_conf.yml
    - ../../vars/dell_os_installation/flavor.yml
    - ./raid/config.yml

  tasks:
    - include_tasks: ./raid/main.yml
    - set_fact:
        SSH_CMD: "sshpass -p {{IDRAC_DFLT_PW}} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=dev/null {{IDRAC_USER}}@{{inventory_hostname}}"
#    - include_tasks: generate_iso.yml
    - include_tasks: setup_passwordless_login.yml
    - include_tasks: bios_settings.yml
    - include_tasks: dell_install_os.yml

    - set_fact:
        select_cmd: ""
    - set_fact:
        select_cmd: "{{select_cmd}} key down"
      with_sequence: count="{{(BOOT_OPTION_NUMBER|int)-1}}"
    - set_fact:
        select_cmd: "{{select_cmd}} sleep 5 key enter"
    # - debug: msg="vncdotool -s {{inventory_hostname}}::{{VNC_PORT}} -p {{VNC_PASSWORD}} expect {{playbook_dir}}/../files/automation_support_images/boot_select.png 0 {{select_cmd}}"
    - pause: minutes=4
    - shell: "vncdotool -s {{inventory_hostname}}::{{VNC_PORT}} -p {{VNC_PASSWORD}} expect {{playbook_dir}}/../../files/dell_os_installation/automation_support_images/boot_select.png 0 {{select_cmd}}"
      delegate_to: localhost

    - pause: minutes=15
    - include_tasks: assign_oam.yml

    - include_tasks: watch_out.yml

    - include_tasks: setup_pwdless_ubuntu.yml
    - include_tasks: bring_oam_up.yml
    - include_tasks: install_license_patches.yml
#    - pause:
#        minutes: 10
#    - include_tasks: watch_out.yml

#    - include_tasks: setup_pwdless_ubuntu.yml
#    - include_tasks: bring_oam_up.yml
#    - include_tasks: controller_config.yml
    - pause:
       minutes: 35
    - include_tasks: watch_out.yml
    - include_tasks: setup_pwdless_ubuntu.yml
   # - include_tasks: bring_oam_up.yml
    - include_tasks: network_config.yml
    - include_tasks: add_host.yml
    - include_tasks: pre_pxe_boot.yml
    - include_tasks: open_stack_flavor.yml

    # - debug:
    #     msg: "After completion of OS Installation please assign OAM IP, copy license and patches, install patches, complete controller configuration and execute network_host_setup.sh"
#    - pause:
#       minutes: 25

    # - name: "Ping OAM"
    #   shell: "ping -c 2 -W 10 {{OAM_CONF[inventory_hostname]['OAM_IP']}}"
    #   register: ping_res
    #   delegate_to: localhost
    #
    # - set_fact:
    #     ping_fail: ping_res.failed
    #
    # - pause:
    #     minutes: 3
    #   when: ping_res.failed

    # - debug:
    #     msg: "{{OAM_CONF[inventory_hostname]}}"

    # - name: "Retry PING OAM"
    #   shell: "ping -c 2 -W 10 {{OAM_CONF[inventory_hostname]['OAM_IP']}}"
    #   register: ping1_res
    #   delegate_to: localhost
    #   when: ping_res.failed
    #
    # - set_fact:
    #     ping_fail: ping1_res.failed
    #   when: ping1_res.failed is defined
    #
    # - fail:
    #     msg: "OAM is not reachable"
    #   when: ping_fail

#    - include_tasks: setup_pwdless_ubuntu.yml
#    - include_tasks: install_license_patches.yml

#    - include_tasks: change_pwd.yml
