- name: Read attribute value
  xml:
    xmlstring: "{{lookup('file', '{{playbook_dir}}/../../files/dell_os_installation/host_config.xml') | regex_replace('xmlns=.*>', '>')}}"
    xpath: /hosts/host/idrac_ip
    content: text
  register: idrac_ip

- name: Read attribute value
  xml:
    xmlstring: "{{lookup('file', '{{playbook_dir}}/../../files/dell_os_installation/host_config.xml') | regex_replace('xmlns=.*>', '>')}}"
    xpath: /hosts/host/idrac_user
    content: text
  register: idrac_user

- name: Read attribute value
  xml:
    xmlstring: "{{lookup('file', '{{playbook_dir}}/../../files/dell_os_installation/host_config.xml') | regex_replace('xmlns=.*>', '>')}}"
    xpath: /hosts/host/idrac_pass
    content: text
  register: idrac_pass

- include_tasks: ./pxe_boot.yml ip_addr="{{item.0.idrac_ip}}" r_user="{{item.1.idrac_user}}" r_pass="{{item.2.idrac_pass}}"
  with_together:
    - "{{idrac_ip.matches}}"
    - "{{idrac_user.matches}}"
    - "{{idrac_pass.matches}}"
