# - include_tasks: query_db.yml QUERY="select id from nsd_descriptor where name='{{NSD_Name}}' AND version='{{NSD_Version}}'"

- set_fact:
    SOURCE_NSD: "{{NSD_Name}}-{{NSD_VERSION}}"
    TARGET_NSD: "{{NSD_Name}}-{{NEW_NSD_VERSION}}"


- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost


- include_tasks: ./https_request_no_template_quick.yml
  vars:
    URL: "{{PREPROD_UPGRADE_URL}}"
    METHOD: "POST"
    PAYLOAD: "rowData={\"sourcensd\":\"{{SOURCE_NSD}}\",\"targetnsd\":\"{{TARGET_NSD}}\"}"

- debug: msg="{{http_resp}}"
