# - include_tasks: query_db.yml QUERY="select id from nsd_descriptor where name='{{NSD_Name}}' AND version='{{NSD_Version}}'"
#
# - set_fact:
#     NSD_ID: "{{RESP.stdout_lines.0}}"
#     TARGET_NSD_VERSION: "{{NSD_Version}}"
#
# - name: Preproduction Abort
#   include_tasks: https_request.yml
#   vars:
#       URL:      "{{ PREPROD_ABORT_URL}}"
#       METHOD:   "POST"
#       PAYLOAD:  "PREPROD_UPGRADE_ABORT.j2"

- set_fact:
    VNFD_QUERY: ""
- set_fact:
    VNFD_QUERY: "{{VNFD_QUERY}} OR (vnfd_id='{{item.key}}' AND version='{{item.value['NEW_VERSION']}}')"
  with_dict: "{{VNFD_UPGRADE_PARAMS}}"

- include_tasks: ../query_db.yml QUERY="select id from vnfd_descriptor where {{VNFD_QUERY[3:]}}"

- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- include_tasks: ./https_request_no_template_quick.yml
  vars:
    URL: "{{PREPROD_ABORT_URL}}?sourcensd={{NSD_Name}}-{{NSD_VERSION}}&targetnsd={{NSD_Name}}-{{NEW_NSD_VERSION}}"
    METHOD: "POST"
    PAYLOAD: "rowData={\"id\":\"\",\"srcnsd\":\"{{NSD_Name}}\",\"srcnsdVersion\":\"{{NSD_VERSION}}\",\"targetnsd\":\"{{NSD_Name}}\",\"targetnsdVersion\":\"{{NEW_NSD_VERSION}}\",\"status\":\"PROCESSING\",\"vnfmMode\":\"WITH_VIM_ACCESS\",\"vnfdId\":\"6\"}"
  with_items: '{{RESP.stdout_lines}}'

- debug:
    msg:
    - ""
    - ""
    - "################################################################"
    - "################################################################"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###           PREPRODUCTION ABORT WAS SUCCESSFUL             ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "################################################################"
    - "################################################################"
    - ""
    - ""
