# - include_tasks: query_db.yml QUERY="select id from nsd_descriptor where name='{{NSD_Name}}' AND version='{{NSD_Version}}'"
#
# - set_fact:
#     NSD_ID: "{{RESP.stdout_lines.0}}"
#     TARGET_NSD_VERSION: "{{NSD_Version}}"
#
# - name: Production Upgrade
#   include_tasks: https_request.yml
#   vars:
#       URL:      "{{ PROD_UPGRADE_URL}}"
#       METHOD:   "POST"
#       PAYLOAD:  "PREPROD_UPGRADE_ABORT.j2"


- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- include_tasks: ./https_request_no_template_quick.yml
  vars:
    URL: "{{PROD_UPGRADE_URL}}"
    METHOD: "POST"
    PAYLOAD: "rowData={\"sourcensd\":\"{{NSD_Name}}-{{NSD_VERSION}}\",\"targetnsd\":\"{{NSD_Name}}-{{NEW_NSD_VERSION}}\"}"
