#CHANGE_VNFD_VERSION
- name: Get Namespace
  shell: "grep -o 'xmlns=.*>' {{file}} | grep -o '\".*\"'"
  register: VNFD_NAMESPACE
  delegate_to: localhost

- set_fact:
    VNFD_NAMESPACE: "{{VNFD_NAMESPACE.stdout_lines.0}}"

- name: Get VNFD ID
  xml:
    xmlstring: "{{lookup('file', '{{file}}') | regex_replace('xmlns=.*>', '>')}}"
    xpath: vnfd-list/vnfd-id
    content: text
  register: VNFD_ID
  delegate_to: localhost

- name: Update VNFD version if in upgrade list
  xml:
    xmlstring: "{{lookup('file', '{{file}}') | regex_replace('xmlns=.*>', '>')}}"
    xpath: vnfd-list/descriptor-version
    value: "{{VNFD_UPGRADE_PARAMS[VNFD_ID.matches[0]['vnfd-id']]['NEW_VERSION']}}"
  register: vnfd_xml
  delegate_to: localhost
  when: VNFD_ID.matches[0]['vnfd-id'] in VNFD_UPGRADE_PARAMS

- name: Update VNFD version if in upgrade list
  xml:
    xmlstring: "{{vnfd_xml.xmlstring[39:]}}"
    xpath: vnfd-list/version
    value: "{{VNFD_UPGRADE_PARAMS[VNFD_ID.matches[0]['vnfd-id']]['NEW_VERSION']}}"
  register: vnfd_xml
  delegate_to: localhost
  when: VNFD_ID.matches[0]['vnfd-id'] in VNFD_UPGRADE_PARAMS

- name: Update VNFD image name if in upgrade list
  xml:
    xmlstring: "{{vnfd_xml.xmlstring[39:]}}"
    xpath: vnfd-list/vdu/vm-image
    value: "{{VNFD_UPGRADE_PARAMS[VNFD_ID.matches[0]['vnfd-id']]['NEW_IMAGE_NAME']}}"
  register: vnfd_xml
  delegate_to: localhost
  when: VNFD_ID.matches[0]['vnfd-id'] in VNFD_UPGRADE_PARAMS

- name: Update life-cycle-state-metadata if in upgrade list
  xml:
    xmlstring: "{{vnfd_xml.xmlstring[39:]}}"
    xpath: vnfd-list/vdu/life-cycle-state-metadata
    value: "{{VNFD_UPGRADE_PARAMS[VNFD_ID.matches[0]['vnfd-id']]['NEW_LCMD_NAME']}}"
  register: vnfd_xml
  delegate_to: localhost
  when: VNFD_ID.matches[0]['vnfd-id'] in VNFD_UPGRADE_PARAMS

- copy: content="{{vnfd_xml.xmlstring[39:]|replace('<vnfd>','<vnfd xmlns='+VNFD_NAMESPACE+'>')}}" dest={{file}}
  when: vnfd_xml.xmlstring is defined
  delegate_to: localhost
