- set_fact:
    orig_xml_string: "{{lvnd_xml.xmlstring}}"

- name: Get VNF Dependency list
  xml:
    xmlstring: "{{lvnd_xml.xmlstring}}"
    xpath: "lvnd-list/lvn/constituent-vnf[{{const_index}}]/vnf-depends-on/vnf-list/vnfd-id"
    content: text
  register: VNF_DEPENDENCY_LIST
  delegate_to: localhost
  ignore_errors: yes


- set_fact:
    VNF_DEPENDENCY_LIST:
        matches: []
  when: VNF_DEPENDENCY_LIST.matches is not defined

- set_fact:
    VNF_DEPENDENCY_LIST_UPDT_IND: []

- set_fact:
    VNF_DEPENDENCY_LIST_UPDT_IND: "{{VNF_DEPENDENCY_LIST_UPDT_IND}} + [ { \"VNFD_ID\": \"{{node_matches['vnfd-id']}}\", \"NODE_INDEX\":  {{node_ind|int + 1}} } ]"
  when: node_matches['vnfd-id'] in VNFD_UPGRADE_PARAMS
  loop: "{{VNF_DEPENDENCY_LIST.matches}}"
  loop_control:
    loop_var: node_matches
    index_var: node_ind

- set_fact:
    lvnd_xml:
        results:
          - xmlstring: "{{lvnd_xml.xmlstring}}"

- xml:
    xmlstring: "{{lvnd_xml.results[((lvnd_xml.results|length|int)-1)].xmlstring}}"
    xpath: "lvnd-list/lvn/constituent-vnf[{{const_index}}]/vnf-depends-on/vnf-list[{{repl['NODE_INDEX']}}]/vnf-version"
    value: "{{VNFD_UPGRADE_PARAMS[repl['VNFD_ID']].NEW_VERSION}}"
  register: lvnd_xml
  loop: "{{VNF_DEPENDENCY_LIST_UPDT_IND}}"
  loop_control:
    loop_var: repl
  delegate_to: localhost

- set_fact:
    lvnd_xml:
        xmlstring: "{{lvnd_xml.results[((lvnd_xml.results|length|int)-1)].xmlstring[39:]}}"
  when: not lvnd_xml.skipped is defined

- set_fact:
    lvnd_xml:
        xmlstring: "{{orig_xml_string}}"
  when: lvnd_xml.skipped is defined
