- name: Get Namespace
  shell: "grep -o 'xmlns=.*>' {{FILE_WTF}} | grep -o '\".*\"'"
  register: LCMD_NAMESPACE
  delegate_to: localhost

- set_fact:
    MODDED_XML_STR: "{{lookup('file', '{{FILE_WTF}}') | regex_replace('xmlns=.*>', '>')}}"

- xml:
    xmlstring: "{{MODDED_XML_STR}}"
    xpath: "{{VDO_XPATH_WTF}}"
    value: "[{{REPLACEABLE_JSON_WTF}}]"
  register: new_lcmd_xml
  delegate_to: localhost

- copy: content="{{new_lcmd_xml.xmlstring[39:]|replace('\"','&quot;')|replace('<vdu-descriptor>','<vdu-descriptor xmlns='+LCMD_NAMESPACE.stdout_lines.0+'>')|replace('&amp;amp;quot;','&amp;quot;')}}" dest="{{FILE_WTF}}"
  delegate_to: localhost
