- set_fact:
    images_info: []

- set_fact:
    images_info: "{{images_info}} + [ {'name':'{{item.value.NEW_IMAGE_NAME}}', 'path': '{{item.value.NEW_IMAGE_LINK}}'} ]"
  with_dict: "{{VNFD_UPGRADE_PARAMS}}"

- name: "Get Tenant Id for Tenant {{ Tenant_Name}}"
  include_tasks: ../query_db.yml QUERY="SELECT id FROM cloud_tenant_config WHERE name='{{Tenant_Name}}'"

- set_fact:
    Tenant_id: "{{ RESP.stdout_lines.0 }}"

- include_tasks: ../Image_save_incl.yml item="{{item}}"
  with_items: "{{images_info}}"

- include_tasks: ../Image_onboard_incl.yml item="{{item}}"
  with_items: "{{images_info}}"

- set_fact:
    IMAGE_QUERY_BUILDER: ""

- set_fact:
    IMAGE_QUERY_BUILDER: "{{IMAGE_QUERY_BUILDER}}OR  name='{{item.name}}'"
  with_items: "{{images_info}}"

- command: "mysql -u{{ MYSQL_USER }} -p{{ MYSQL_PASSWD }} {{ MYSQL_DB }} -sN -e \"SELECT count(status) FROM image_config_status  WHERE fk_image_config in (select id from image_config where {{IMAGE_QUERY_BUILDER[3:]}}) AND ((not status='Uploaded') AND (not status='InUse')) \" "
  register: STATUS_RESP
  remote_user: "{{CMS_IP_SYSUSER}}"
  retries: "{{DESCRIPTOR_RETRIES}}"
  delay: "{{ DELAY }}"
  until: STATUS_RESP.stdout == "0"
  ignore_errors: yes

- debug:
    msg:
    - ""
    - ""
    - "################################################################"
    - "################################################################"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###         ALL IMAGES WERE UPLOADED SUCCESSFULLY!!!         ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "################################################################"
    - "################################################################"
    - ""
    - ""
  when: ( STATUS_RESP.stdout == "0")

- fail:
    msg:
    - ""
    - ""
    - "################################################################"
    - "################################################################"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###          {{STATUS_RESP.stdout}} IMAGES WERE NOT UPLOADED SUCCESSFULLY         ###"
    - "###  PLEASE CHECK THE LOGS, RESOLVE THE ISSUE AND TRY AGAIN  ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "###                                                          ###"
    - "################################################################"
    - "################################################################"
    - ""
    - ""
  when: not ( STATUS_RESP.stdout == "0")
