---

    - name: Read VNFD_Id attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_Id }}"
         content: text
      register: xmlIDresp
      delegate_to: localhost

    - debug:
        var: xmlIDresp.matches[0]["vnfd-id"]

    - name: Read NSD_Version attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_Version }}"
         content: text
      register: xmlVERresp
      delegate_to: localhost

    - debug:
        var: xmlVERresp.matches[0]["descriptor-version"]

    - name: Read VNFD_VDU_Id attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_VDU_Id }}"
         content: text
      register: xmlVDUIDresp
      delegate_to: localhost

    - debug:
        var: xmlVDUIDresp.matches[0].id


    - include_tasks : ./OfflineConfig_Config_VDU_tasks_Add.yml
      vars:
         CONFIG_VDU_FILE: "{{config_file_name}}"

      with_items: "{{ CONFIG_FILES }}"
      loop_control:
          loop_var: config_file_name
