---

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select id from nsd_descriptor where version='{{NSD_Vers}}'"
      when: NSD_Vers is defined
    - set_fact: NSD_DB_Id2="{{RESP.stdout_lines.0}}"
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select nsd_id from nsd_descriptor where version='{{NSD_Vers}}'"
      when: NSD_Vers is defined
    - set_fact: NSD_Id="{{RESP.stdout_lines.0}}"
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select name from nsd_descriptor where version='{{NSD_Vers}}'"
      when: NSD_Vers is defined
    - set_fact: NSD_Name="{{RESP.stdout_lines.0}}"
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select status from nsd_descriptor_status where fk_nsd_descriptor='{{NSD_DB_Id2}}'"
      when: NSD_DB_Id2 is defined
    - set_fact: NSD_Id_Status="{{RESP.stdout_lines.0}}"
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select unique_id from  nsd_descriptor_status where fk_nsd_descriptor='{{NSD_DB_Id2}}'"
      when: NSD_DB_Id2 is defined
    - set_fact: NSD_Unique_Id="{{RESP.stdout_lines.0}}"
      when: RESP.stdout_lines.0 is defined

    - name: fail the play if the NSD_Id_Status not ONBOARDED
      debug:
        msg: "NSD is in {{NSD_Id_Status}} state... NSD is not in ONBOARDED State"
      when: (NSD_Id_Status is defined) and not ( NSD_Id_Status|lower == "Onboarded"|lower )

    - debug:
        msg: "{{NSD_DB_Id2}} {{NSD_Id_Status}}"

    - include_tasks: ./Deploy_NSD_tasks_Status.yml
      vars:
        NSD_Vers_1: "{{NSD_Vers}}"
        NSD_DB_Ids: "{{NSD_DB_Id2}}"
        NSD_Id_1: "{{NSD_Id}}"
      when: (NSD_Id_Status is defined) and (NSD_Id_Status|lower == "Onboarded"|lower)
