---

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select nsd_id from nsd_descriptor where id='{{NSD_DB_Id1}}'"
      when: NSD_DB_Id1 is defined
    - set_fact: NSD_Id={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select name from nsd_descriptor where id='{{NSD_DB_Id1}}'"
      when: NSD_DB_Id1 is defined
    - set_fact: NSD_Name={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select version from nsd_descriptor where id='{{NSD_DB_Id1}}'"
      when: NSD_DB_Id1 is defined
    - set_fact: NSD_Vers={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select status from nsd_descriptor_status where fk_nsd_descriptor='{{NSD_DB_Id1}}'"
      when: NSD_DB_Id1 is defined
    - set_fact: NSD_Id_Status={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select unique_id from  nsd_descriptor_status where fk_nsd_descriptor='{{NSD_DB_Id1}}'"
      when: NSD_DB_Id1 is defined
    - set_fact: NSD_Unique_Id={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - name: fail the play if the NSD_Id_Status not ONBOARDED
      debug:
        msg: "NSD is in {{NSD_Id_Status}} state... NSD is not in DEPLOYED State"
      when: not (( NSD_Id_Status|lower == "Deployed"|lower) or ( NSD_Id_Status|lower == "InUse"|lower))

    - include_tasks: ./Terminate_NSD_tasks_Status.yml
      vars:
         NSD_Vers_1: "{{NSD_Vers}}"
         NSD_DB_Ids: "{{NSD_DB_Id1}}"
      when: (NSD_Id_Status is defined) and (( NSD_Id_Status|lower == "Deployed"|lower) or ( NSD_Id_Status|lower == "InUse"|lower))
