---

    - name: Read VNFD_Id attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_Id }}"
         content: text
      register: xmlIDresp
      delegate_to: localhost

    - set_fact:
        VNFD_Id: "{{xmlIDresp.matches[0]['vnfd-id']}}"

    - name: Read NSD_Version attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_Version }}"
         content: text
      register: xmlVERresp
      delegate_to: localhost

    - set_fact:
        NSD_Version: "{{xmlVERresp.matches[0]['descriptor-version']}}"

    - name: Read VNFD_VDU_Id attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VNFD_VDU_Id }}"
         content: text
      register: xmlVDUIDresp
      delegate_to: localhost

    - set_fact:
        VNFD_VDU_Id: "{{xmlVDUIDresp.matches[0].id}}"


    - include_tasks : ./ConfigModel_Yang_VDU_tasks.yml
                          YANG_VDU_FILE="{{yang_file_name}}"
                          VNFD_VDU_Id_5="{{VNFD_VDU_Id}}"
                          NSD_Version_5="{{NSD_Version}}"
                          VNFD_Id_5="{{VNFD_Id}}"

      with_items: "{{ YANG_FILES }}"
      loop_control:
          loop_var: yang_file_name
