- set_fact:
    NAME_TO_BE_USED: "{{CONFIG_FILE_NAME[:30] | replace('.xml', '')}}-{{VDU_ID}}"
    FILE_ABS_PATH: "{{DESCRIPTOR_PATH}}/{{DESCRIPTOR_INFO.0}}/Config/{{CONFIG_FILE_NAME}}"
- set_fact:
    NAME_TO_BE_USED: "{{NAME_TO_BE_USED[:40]}}"

- shell: "curl -s  -k -X  POST -F file=@'{{FILE_ABS_PATH}}; type = text/xml' -F rowData=\"{'id':'',  'name':'{{NAME_TO_BE_USED}}',  'fkDataModel':'{{DATA_MODEL_DB_ID}}',  'attachFile':'{{CONFIG_FILE_NAME}}'}\" --cookie '{{login_response.set_cookie}}' {{IMPORT_SNAPSHOT_CONFIG_URL}}"
  register: curl_resp
  delegate_to: localhost

- debug: msg="{{curl_resp}}"
