CREATE PRIMARY INDEX epdg_bucket_PK1 ON epdg_bucket USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX epdg_bucket_PK2 ON epdg_bucket USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX epdg_bucket_PK3 ON epdg_bucket USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx1 ON epdg_bucket(APP_OID) WHERE KTAB='epdgMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx2 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecATBriefMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx3 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecACTMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx4 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecAllTMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx5 ON epdg_bucket(APP_OID) WHERE KTAB='ikeVnfAppMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx6 ON epdg_bucket(APP_OID) WHERE KTAB='ssuVNFAppMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx7 ON epdg_bucket(VNFID) WHERE KTAB='ipsecACTMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx8 ON epdg_bucket(VNFID) WHERE KTAB='ipsecAllTMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx9 ON epdg_bucket(VNFID,Timestamp) WHERE KTAB= 'ssuVNFPAppMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx10 ON epdg_bucket(VNFID,TIMESTAMP) WHERE KTAB= 'ipsecATBriefMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx11 ON epdg_bucket(VNFPriority) WHERE KTAB='ssuVNFPAppMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx12 ON epdg_bucket(VNFIDPriority,APP_OID) WHERE KTAB='epdgMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx13 ON epdg_bucket(IKE_SYNC_KEY_VM_ID) WHERE KTAB='ikeVnfAppMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx14 ON epdg_bucket(epdgappinterfaceids) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup1 ON epdg_bucket(APP_OID) WHERE KTAB='epdgMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup2 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecATBriefMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup3 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecACTMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup4 ON epdg_bucket(APP_OID) WHERE KTAB='ipsecAllTMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup5 ON epdg_bucket(APP_OID) WHERE KTAB='ikeVnfAppMap' USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup6 ON epdg_bucket(APP_OID) WHERE KTAB='ssuVNFAppMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup7 ON epdg_bucket(VNFID) WHERE KTAB='ipsecACTMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup8 ON epdg_bucket(VNFID) WHERE KTAB='ipsecAllTMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup9 ON epdg_bucket(VNFID,Timestamp) WHERE KTAB= 'ssuVNFPAppMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup10 ON epdg_bucket(VNFID,TIMESTAMP) WHERE KTAB= 'ipsecATBriefMap' USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup11 ON epdg_bucket(VNFPriority) WHERE KTAB='ssuVNFPAppMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup12 ON epdg_bucket(VNFIDPriority,APP_OID) WHERE KTAB='epdgMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup13 ON epdg_bucket(IKE_SYNC_KEY_VM_ID) WHERE KTAB='ikeVnfAppMap' USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX epdg_bucket_idx_dup14 ON epdg_bucket(epdgappinterfaceids) USING GSI WITH {"nodes":["node1_IP:8091"]};
