CREATE PRIMARY INDEX `sessiondb_tas_PK1` ON `sessiondb_tas` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessiondb_tas_PK2` ON `sessiondb_tas` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessiondb_tas_PK3` ON `sessiondb_tas` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx1` ON `sessiondb_tas`(`msisdn`,`app_oid`) WHERE (`KTAB` = "SccasMeta") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx2` ON `sessiondb_tas`(`vmid`) WHERE (`KTAB` = "SccasMeta") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx3` ON `sessiondb_tas`(`msisdn`,`app_oid`) WHERE (`KTAB` = "TasMeta") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx4` ON `sessiondb_tas`(`vmid`) WHERE (`KTAB` = "TasMeta") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx5` ON `sessiondb_tas`(`Tasappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx_dup1` ON `sessiondb_tas`(`msisdn`,`app_oid`) WHERE (`KTAB` = "SccasMeta")  USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx_dup2` ON `sessiondb_tas`(`vmid`) WHERE (`KTAB` = "SccasMeta") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx_dup3` ON `sessiondb_tas`(`msisdn`,`app_oid`) WHERE (`KTAB` = "TasMeta") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx_dup4` ON `sessiondb_tas`(`vmid`) WHERE (`KTAB` = "TasMeta") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessiondb_tas_idx_dup5` ON `sessiondb_tas`(`Tasappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
