CREATE PRIMARY INDEX SCNfvCouchbase_PK ON SCNfvCouchbase USING GSI;
CREATE INDEX SCNfvCouchbase_idx1 ON SCNfvCouchbase(VMID) WHERE KTAB= 'ccsVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx2 ON SCNfvCouchbase(VMID) WHERE KTAB= 'MPCVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx3 ON SCNfvCouchbase(VMID) WHERE KTAB= 'MPPVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx4 ON SCNfvCouchbase(VMID) WHERE KTAB= 'atcVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx5 ON SCNfvCouchbase(VMID) WHERE KTAB= 'tcVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx6 ON SCNfvCouchbase(VMID) WHERE KTAB= 'profileVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx7 ON SCNfvCouchbase(VMID) WHERE KTAB = 'pcscfVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx8 ON SCNfvCouchbase(VMID) WHERE KTAB = 'atcfVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx9 ON SCNfvCouchbase(VMID) WHERE KTAB = 'ibcfVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx10 ON SCNfvCouchbase(VMID) WHERE KTAB = 'eatfVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx11 ON SCNfvCouchbase(VMID) WHERE KTAB = 'trfVmAppMap' USING GSI;
CREATE INDEX SCNfvCouchbase_idx12 ON SCNfvCouchbase(Uagappinterfaceids) USING GSI;
