CREATE PRIMARY INDEX `sessionDBVLB_EPDG_PK1` ON `sessionDBVLB_EPDG` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_EPDG_PK2` ON `sessionDBVLB_EPDG` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_EPDG_PK3` ON `sessionDBVLB_EPDG` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx1` ON `sessionDBVLB_EPDG`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx2` ON `sessionDBVLB_EPDG`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx3` ON `sessionDBVLB_EPDG`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx4` ON `sessionDBVLB_EPDG`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx_dup1` ON `sessionDBVLB_EPDG`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx_dup2` ON `sessionDBVLB_EPDG`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx_dup3` ON `sessionDBVLB_EPDG`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_EPDG_idx_dup4` ON `sessionDBVLB_EPDG`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
