CREATE PRIMARY INDEX `sessionDBVLB_VMAS_PK1` ON `sessionDBVLB_VMAS` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_VMAS_PK2` ON `sessionDBVLB_VMAS` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_VMAS_PK3` ON `sessionDBVLB_VMAS` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx1` ON `sessionDBVLB_VMAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx2` ON `sessionDBVLB_VMAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx3` ON `sessionDBVLB_VMAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx4` ON `sessionDBVLB_VMAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx_dup1` ON `sessionDBVLB_VMAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx_dup2` ON `sessionDBVLB_VMAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx_dup3` ON `sessionDBVLB_VMAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_VMAS_idx_dup4` ON `sessionDBVLB_VMAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
