CREATE PRIMARY INDEX `sessionDBVLB_AGW_PK1` ON `sessionDBVLB_AGW` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_AGW_PK2` ON `sessionDBVLB_AGW` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_AGW_PK3` ON `sessionDBVLB_AGW` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx1` ON `sessionDBVLB_AGW`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx2` ON `sessionDBVLB_AGW`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx3` ON `sessionDBVLB_AGW`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx4` ON `sessionDBVLB_AGW`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx_dup1` ON `sessionDBVLB_AGW`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx_dup2` ON `sessionDBVLB_AGW`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx_dup3` ON `sessionDBVLB_AGW`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_AGW_idx_dup4` ON `sessionDBVLB_AGW`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
