CREATE PRIMARY INDEX `sessionDBVLB_SCEF_PK` ON `sessionDBVLB_SCEF` USING GSI;
CREATE INDEX `sessionDBVLB_SCEF_idx1` ON `sessionDBVLB_SCEF`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_SCEF_idx2` ON `sessionDBVLB_SCEF`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_SCEF_idx3` ON `sessionDBVLB_SCEF`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_SCEF_idx4` ON `sessionDBVLB_SCEF`(`vlbappinterfaceids`) USING GSI;
