CREATE PRIMARY INDEX `sessionDBVLB_IPSM_PK1` ON `sessionDBVLB_IPSM` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_IPSM_PK2` ON `sessionDBVLB_IPSM` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_IPSM_PK3` ON `sessionDBVLB_IPSM` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx1` ON `sessionDBVLB_IPSM`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx2` ON `sessionDBVLB_IPSM`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx3` ON `sessionDBVLB_IPSM`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx4` ON `sessionDBVLB_IPSM`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx_dup1` ON `sessionDBVLB_IPSM`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx_dup2` ON `sessionDBVLB_IPSM`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx_dup3` ON `sessionDBVLB_IPSM`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_IPSM_idx_dup4` ON `sessionDBVLB_IPSM`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
