CREATE PRIMARY INDEX `sessionDBVLB_CSCF_PK` ON `sessionDBVLB_CSCF` USING GSI;
CREATE INDEX `sessionDBVLB_CSCF_idx1` ON `sessionDBVLB_CSCF`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_CSCF_idx2` ON `sessionDBVLB_CSCF`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_CSCF_idx3` ON `sessionDBVLB_CSCF`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_CSCF_idx4` ON `sessionDBVLB_CSCF`(`vlbappinterfaceids`) USING GSI;
