CREATE PRIMARY INDEX `sessionDBVLB_TAS_PK1` ON `sessionDBVLB_TAS` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_TAS_PK2` ON `sessionDBVLB_TAS` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_TAS_PK3` ON `sessionDBVLB_TAS` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx1` ON `sessionDBVLB_TAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx2` ON `sessionDBVLB_TAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx3` ON `sessionDBVLB_TAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx4` ON `sessionDBVLB_TAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx_dup1` ON `sessionDBVLB_TAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx_dup2` ON `sessionDBVLB_TAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx_dup3` ON `sessionDBVLB_TAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_TAS_idx_dup4` ON `sessionDBVLB_TAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
