CREATE PRIMARY INDEX `sessionDBVLB_IPSM_PK` ON `sessionDBVLB_IPSM` USING GSI;
CREATE INDEX `sessionDBVLB_IPSM_idx1` ON `sessionDBVLB_IPSM`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_IPSM_idx2` ON `sessionDBVLB_IPSM`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_IPSM_idx3` ON `sessionDBVLB_IPSM`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_IPSM_idx4` ON `sessionDBVLB_IPSM`(`vlbappinterfaceids`) USING GSI;
