CREATE PRIMARY INDEX `sessionDBVLB_UCCAS_PK1` ON `sessionDBVLB_UCCAS` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_UCCAS_PK2` ON `sessionDBVLB_UCCAS` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_UCCAS_PK3` ON `sessionDBVLB_UCCAS` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx1` ON `sessionDBVLB_UCCAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx2` ON `sessionDBVLB_UCCAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx3` ON `sessionDBVLB_UCCAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx4` ON `sessionDBVLB_UCCAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx_dup1` ON `sessionDBVLB_UCCAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx_dup2` ON `sessionDBVLB_UCCAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx_dup3` ON `sessionDBVLB_UCCAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_UCCAS_idx_dup4` ON `sessionDBVLB_UCCAS`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
