CREATE PRIMARY INDEX `sessionDBVLB_WSG_PK1` ON `sessionDBVLB_WSG` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_WSG_PK2` ON `sessionDBVLB_WSG` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_WSG_PK3` ON `sessionDBVLB_WSG` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx1` ON `sessionDBVLB_WSG`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx2` ON `sessionDBVLB_WSG`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx3` ON `sessionDBVLB_WSG`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx4` ON `sessionDBVLB_WSG`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx_dup1` ON `sessionDBVLB_WSG`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx_dup2` ON `sessionDBVLB_WSG`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx_dup3` ON `sessionDBVLB_WSG`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_WSG_idx_dup4` ON `sessionDBVLB_WSG`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
