CREATE PRIMARY INDEX `sessionDBVLB_UAG_MP_PK` ON `sessionDBVLB_UAG_MP` USING GSI;
CREATE INDEX `sessionDBVLB_UAG_MP_idx1` ON `sessionDBVLB_UAG_MP`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_UAG_MP_idx2` ON `sessionDBVLB_UAG_MP`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_MP_idx3` ON `sessionDBVLB_UAG_MP`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_MP_idx4` ON `sessionDBVLB_UAG_MP`(`vlbappinterfaceids`) USING GSI;
