CREATE PRIMARY INDEX `sessionDBVLB_UAG_TC_PK` ON `sessionDBVLB_UAG_TC` USING GSI;
CREATE INDEX `sessionDBVLB_UAG_TC_idx1` ON `sessionDBVLB_UAG_TC`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_UAG_TC_idx2` ON `sessionDBVLB_UAG_TC`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_TC_idx3` ON `sessionDBVLB_UAG_TC`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_TC_idx4` ON `sessionDBVLB_UAG_TC`(`vlbappinterfaceids`) USING GSI;
