CREATE PRIMARY INDEX `sessionDBVLB_UCCAS_PK` ON `sessionDBVLB_UCCAS` USING GSI;
CREATE INDEX `sessionDBVLB_UCCAS_idx1` ON `sessionDBVLB_UCCAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_UCCAS_idx2` ON `sessionDBVLB_UCCAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UCCAS_idx3` ON `sessionDBVLB_UCCAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UCCAS_idx4` ON `sessionDBVLB_UCCAS`(`vlbappinterfaceids`) USING GSI;
