CREATE PRIMARY INDEX `sessionDBVLB_VMAS_PK` ON `sessionDBVLB_VMAS` USING GSI;
CREATE INDEX `sessionDBVLB_VMAS_idx1` ON `sessionDBVLB_VMAS`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_VMAS_idx2` ON `sessionDBVLB_VMAS`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_VMAS_idx3` ON `sessionDBVLB_VMAS`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_VMAS_idx4` ON `sessionDBVLB_VMAS`(`vlbappinterfaceids`) USING GSI;
