CREATE PRIMARY INDEX `sessionDBVLB_EPDG_PK` ON `sessionDBVLB_EPDG` USING GSI;
CREATE INDEX `sessionDBVLB_EPDG_idx1` ON `sessionDBVLB_EPDG`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_EPDG_idx2` ON `sessionDBVLB_EPDG`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_EPDG_idx3` ON `sessionDBVLB_EPDG`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_EPDG_idx4` ON `sessionDBVLB_EPDG`(`vlbappinterfaceids`) USING GSI;
