CREATE PRIMARY INDEX `sessionDBVLB_UAG_SC_PK` ON `sessionDBVLB_UAG_SC` USING GSI;
CREATE INDEX `sessionDBVLB_UAG_SC_idx1` ON `sessionDBVLB_UAG_SC`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI;
CREATE INDEX `sessionDBVLB_UAG_SC_idx2` ON `sessionDBVLB_UAG_SC`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_SC_idx3` ON `sessionDBVLB_UAG_SC`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI;
CREATE INDEX `sessionDBVLB_UAG_SC_idx4` ON `sessionDBVLB_UAG_SC`(`vlbappinterfaceids`) USING GSI;
