CREATE PRIMARY INDEX `sessionDBVLB_SDC_PK1` ON `sessionDBVLB_SDC` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_SDC_PK2` ON `sessionDBVLB_SDC` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_SDC_PK3` ON `sessionDBVLB_SDC` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx1` ON `sessionDBVLB_SDC`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx2` ON `sessionDBVLB_SDC`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx3` ON `sessionDBVLB_SDC`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx4` ON `sessionDBVLB_SDC`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx_dup1` ON `sessionDBVLB_SDC`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx_dup2` ON `sessionDBVLB_SDC`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx_dup3` ON `sessionDBVLB_SDC`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SDC_idx_dup4` ON `sessionDBVLB_SDC`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
