CREATE PRIMARY INDEX `sessionDBVLB_SCEF_PK1` ON `sessionDBVLB_SCEF` USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_SCEF_PK2` ON `sessionDBVLB_SCEF` USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE PRIMARY INDEX `sessionDBVLB_SCEF_PK3` ON `sessionDBVLB_SCEF` USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx1` ON `sessionDBVLB_SCEF`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx2` ON `sessionDBVLB_SCEF`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node1_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx3` ON `sessionDBVLB_SCEF`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx4` ON `sessionDBVLB_SCEF`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx_dup1` ON `sessionDBVLB_SCEF`(`VMID`,`Timestamp`,`OP_TYPE`) WHERE ((`KEYFLAG` = "1") and (`KTAB` = "SipData")) USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx_dup2` ON `sessionDBVLB_SCEF`(`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node2_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx_dup3` ON `sessionDBVLB_SCEF`(`VNFID`,`TIMESTAMP`,`APP_OID`) WHERE (`KTAB` = "mNATMap") USING GSI WITH {"nodes":["node3_IP:8091"]};
CREATE INDEX `sessionDBVLB_SCEF_idx_dup4` ON `sessionDBVLB_SCEF`(`vlbappinterfaceids`) USING GSI WITH {"nodes":["node1_IP:8091"]};
