- shell: "cd {{playbook_dir}}/../../files/heat_templates/crdl/ && for env_file in `(ls *Cluster*{{C_TENANT}}*.env)`; do echo `(cat $env_file | grep CRDL_db_traffic_ips | cut -d':' -f2 | cut -d'[' -f2 | cut -d']' -f1 | awk '{print $1}')`; done;"
  register: CRDL_CLUSTER_DB_IPS
  delegate_to: localhost

- set_fact:
    CRDL_NODE_DBTRAFFIC_IP_LIST: ""

- set_fact:
    CRDL_NODE_DBTRAFFIC_IP_LIST: "{{CRDL_NODE_DBTRAFFIC_IP_LIST}} {{item}}"
  with_items: "{{CRDL_CLUSTER_DB_IPS.stdout_lines}}"

- shell: "sed -i 's/CRDL_CLUSTER_DB_IPS/{{CRDL_NODE_DBTRAFFIC_IP_LIST[1:]}}/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  delegate_to: localhost

- shell: "sed -i 's/CRDL_BUCKET_NAME/{{CRDL_BUCKET_NAME.split(',')[DATA_INDEX]}}/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  delegate_to: localhost

- shell: "cd {{playbook_dir}}/../../files/heat_templates/crdl/ && ls *Admin*.env"
  register: CRDL_ADMIN_ENVS
  delegate_to: localhost

- shell: "cd {{playbook_dir}}/../../files/heat_templates/crdl/ && cat {{CRDL_ADMIN_ENVS.stdout_lines.0}} | grep CRDL_oam_ips | cut -d':' -f2 | cut -d'[' -f2 | cut -d']' -f1 | awk '{print $1}'"
  register: CRDL_ADMIN_OAM_IP
  delegate_to: localhost

- include_tasks: setup_pwdless_generic.yml PWDLESS_IP="{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}" PWDLESS_USER="{{CRDL_SYS_USER_NAME}}" PWDLESS_PASSWD="{{CRDL_ADMIN_SYS_PASSWORD}}"

- name: "Copy crdl_admin to '~' directory in remote host"
  shell: "sshpass -p {{CRDL_ADMIN_SYS_PASSWORD}} /usr/bin/scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin {{CRDL_SYS_USER_NAME}}@{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}:~/"
  delegate_to: localhost

- name: "Create instance of cluster-{{DATA_INDEX}}"
  shell: "cd ~/crdl_admin/ && source /etc/profile && sed -i 's/inst_id=1/inst_id={{DATA_INDEX}}/g' crdlMon && mv crdlMon.sh crdlMon_{{DATA_INDEX}}.sh && mv crdlMon.cfg crdlMon_{{DATA_INDEX}}.cfg && mv crdlMon crdlMon_{{DATA_INDEX}} && mv loopProcessMon.sh loopProcessMon_{{DATA_INDEX}}.sh && chmod 777 ./*"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Copy crdlMon_{{DATA_INDEX}} to /etc/init.d/"
  shell: "cd ~/crdl_admin/ && cp crdlMon_{{DATA_INDEX}} /etc/init.d/ && cp loopProcessMon_{{DATA_INDEX}}.sh /opt/dbsnmpagent/ && chmod 777 /etc/init.d/crdlMon_{{DATA_INDEX}} && chmod 777 /opt/dbsnmpagent/loopProcessMon_{{DATA_INDEX}}.sh"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Executing crdlMon_{{DATA_INDEX}}.sh"
  shell: "cd ~/crdl_admin/ && source /etc/profile && chmod 777 *.sh && ~/crdl_admin/crdlMon_{{DATA_INDEX}}.sh && chmod 777 /etc/init.d/crdlMon_{{DATA_INDEX}} && cp ~/crdl_admin/* /opt/dbsnmpagent/ && (service crdlMon_{{DATA_INDEX}} start || true) && chkconfig crdlMon_{{DATA_INDEX}} on"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Checking status of crdlMon_{{DATA_INDEX}}"
  shell: "service crdlMon_{{DATA_INDEX}} status"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Restarting crdlMon_{{DATA_INDEX}}"
  shell: "`(/usr/bin/sshpass -pmavenir  ssh {{CRDL_SYS_USER_NAME}}@{{CRDL_ADMIN_OAM_IP.stdout_lines.0}} \"service crdlMon_{{DATA_INDEX}} restart\")` || true"
  delegate_to: "localhost"

- shell: "cd {{playbook_dir}}/../../files/heat_templates/crdl/ && cat {{CRDL_ADMIN_ENVS.stdout_lines.1}} | grep CRDL_oam_ips | cut -d':' -f2 | cut -d'[' -f2 | cut -d']' -f1 | awk '{print $1}'"
  register: CRDL_ADMIN_OAM_IP
  when: CRDL_ADMIN_ENVS.stdout_lines.1 is defined
  delegate_to: localhost

- shell: "sed -i 's/PRIMARY/STANDBY/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  when: CRDL_ADMIN_ENVS.stdout_lines.1 is defined
  delegate_to: localhost

- include_tasks: setup_pwdless_generic.yml PWDLESS_IP="{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}" PWDLESS_USER="{{CRDL_SYS_USER_NAME}}" PWDLESS_PASSWD="{{CRDL_ADMIN_SYS_PASSWORD}}"
  when: CRDL_ADMIN_ENVS.stdout_lines.1 is defined

- name: "Copy crdl_admin to '~' directory in remote host"
  shell: "sshpass -p {{CRDL_ADMIN_SYS_PASSWORD}} /usr/bin/scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin {{CRDL_SYS_USER_NAME}}@{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}:~/"
  when: CRDL_ADMIN_ENVS.stdout_lines.1 is defined
  delegate_to: localhost

- name: "Create instance of cluster-{{DATA_INDEX}}"
  shell: "cd ~/crdl_admin/ && source /etc/profile && sed -i 's/inst_id=1/inst_id={{DATA_INDEX}}/g' crdlMon && mv crdlMon.sh crdlMon_{{DATA_INDEX}}.sh && mv crdlMon.cfg crdlMon_{{DATA_INDEX}}.cfg && mv crdlMon crdlMon_{{DATA_INDEX}} && mv loopProcessMon.sh loopProcessMon_{{DATA_INDEX}}.sh && chmod 777 ./*"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Copy crdlMon_{{DATA_INDEX}} to /etc/init.d/"
  shell: "cd ~/crdl_admin/ && cp crdlMon_{{DATA_INDEX}} /etc/init.d/ && cp loopProcessMon_{{DATA_INDEX}}.sh /opt/dbsnmpagent/ && chmod 777 /etc/init.d/crdlMon_{{DATA_INDEX}} && chmod 777 /opt/dbsnmpagent/loopProcessMon_{{DATA_INDEX}}.sh"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Executing crdlMon_{{DATA_INDEX}}.sh"
  shell: "cd ~/crdl_admin/ && source /etc/profile && chmod 777 *.sh && ~/crdl_admin/crdlMon_{{DATA_INDEX}}.sh && chmod 777 /etc/init.d/crdlMon_{{DATA_INDEX}} && cp ~/crdl_admin/* /opt/dbsnmpagent/ && (service crdlMon_{{DATA_INDEX}} start || true) && chkconfig crdlMon_{{DATA_INDEX}} on"
  when: CRDL_ADMIN_ENVS.stdout_lines.1 is defined
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Checking status of crdlMon_{{DATA_INDEX}}"
  shell: "service crdlMon_{{DATA_INDEX}} status"
  delegate_to: "{{CRDL_ADMIN_OAM_IP.stdout_lines.0}}"
  remote_user: "{{CRDL_SYS_USER_NAME}}"

- name: "Restarting crdlMon_{{DATA_INDEX}}"
  shell: "`(/usr/bin/sshpass -pmavenir  ssh {{CRDL_SYS_USER_NAME}}@{{CRDL_ADMIN_OAM_IP.stdout_lines.0}} \"service crdlMon_{{DATA_INDEX}} restart\")` || true"
  delegate_to: "localhost"

- shell: "sed -i 's/STANDBY/PRIMARY/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  delegate_to: localhost

- shell: "sed -i 's/{{CRDL_NODE_DBTRAFFIC_IP_LIST[1:]}}/CRDL_CLUSTER_DB_IPS/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  delegate_to: localhost

- shell: "sed -i 's/{{CRDL_BUCKET_NAME.split(',')[DATA_INDEX]}}/CRDL_BUCKET_NAME/g' {{playbook_dir}}/../../files/heat_templates/crdl_bucket_admin_configuration/crdl_admin/crdlMon.cfg"
  delegate_to: localhost
