---

- hosts: controller
  gather_facts: no
  vars_files:
    - ../../vars/heat_templates/config.yml

  tasks:
    - name: "Delete old host"
      shell: "rm -rf ~/.ssh/known_hosts"
      delegate_to: localhost
      args:
        warn: false
    - include_tasks: setup_pwdless_ubuntu.yml
    - include_tasks: heat_templates.yml
