---

- hosts: localhost
  gather_facts: no
  vars_files:
    - ../../vars/heat_templates/config.yml

  tasks:
    - name: "Delete old host"
      shell: "rm -rf ~/.ssh/known_hosts"
      delegate_to: localhost
      args:
        warn: false
    - include_tasks: setup_pwdless_generic.yml PWDLESS_IP="{{VNFM1_IP}}" PWDLESS_USER="{{VNFM1_USER}}" PWDLESS_PASSWD="{{VNFM1_PASSWORD}}"

    - shell: "mv /opt/Install/VnfmDBUpgrade/VnfmDBExport.sh /opt/Install/VnfmDBUpgrade/VnfmDBExport_bck.sh"
      remote_user: "{{VNFM1_USER}}"
      delegate_to: "{{VNFM1_IP}}"

    - name: "Copy file VnfmDBExport.sh from {{playbook_dir}}/../../files/heat_templates/ directory in localhost to /opt/Install/VnfmDBUpgrade/ in the remote host"
      copy:
        src: "{{playbook_dir}}/../../files/heat_templates/VnfmDBExport.sh"
        dest: "/opt/Install/VnfmDBUpgrade/"
      remote_user: "{{VNFM1_USER}}"
      delegate_to: "{{VNFM1_IP}}"

    - shell: "rm -rf /tmp/vnfm_db_* && rm -rf /tmp/vnfm_db && chmod +x /opt/Install/VnfmDBUpgrade/VnfmDBExport.sh && source /etc/profile && /opt/Install/VnfmDBUpgrade/VnfmDBExport.sh && mv /tmp/vnfm_db_* /tmp/vnfm_db && cd /tmp/vnfm_db/ && mv /tmp/vnfm_db/vnfm_db*.tgz /tmp/vnfm_db/vnfm_db.tgz"
      remote_user: "{{VNFM1_USER}}"
      delegate_to: "{{VNFM1_IP}}"

    - name: "fetch"
      shell: "sshpass -p {{VNFM1_PASSWORD}} /usr/bin/scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r {{VNFM1_USER}}@{{VNFM1_IP}}:/tmp/vnfm_db/vnfm_db.tgz {{playbook_dir}}/../../files/heat_templates/vnfm_backup/"
      delegate_to: localhost
