- set_fact:
    START: "{{END}}"

- set_fact:
    END: "{{(START|int)+(NUM_PDISKS_IN_R1_VDISK|int)}}"

- set_fact:
    start_index: "{{START|int}}"
- set_fact:
    end_index: "{{((END|int)-1)|int}}"

- include_tasks: generate_seq.yml

- include_tasks: make_raided.yml

- set_fact:
    PDKEY_VAL: ""

- set_fact:
    PDKEY_VAL: "{{PDKEY_VAL + PDISKS[pdisk_ind_num|int] + ','}}"
  with_sequence: "{{start_index}}-{{end_index}}"
  loop_control:
    loop_var: pdisk_ind_num

- name: Creating VirtualDisk with RAID level 1
  shell: "{{SSH_CMD}} racadm raid createvd:{{CTRL_FQDD}} -rl r1 -pdkey:{{PDKEY_VAL[0:-1]}}"
  delegate_to: localhost

- include_tasks: createjobs.yml
- pause: minutes=3
  when: not job_creation.stdout is search("ERROR")
