#[]FQDD, Ctrl_FQDD, raid
#incl deletejobs.yml
#incl raided.yml
#racadm raid createvd:*Ctrl_FQDD* -rl -r0 -pdkey:{{FQDD|join(',')}}

#incl createjobs.yml *Ctrl_FQDD* <---- 
- set_fact:
    NUM_R0_VDISKS: "{{raid_num_props.split(',')[0]|int}}"

- set_fact:
    NUM_PDISKS_IN_R0_VDISK: "{{raid_num_props.split(',')[1]|int}}"

- include_tasks: raidzero_config.yml
  with_sequence: "1-{{NUM_R0_VDISKS}}"
  ignore_errors: yes
  loop_control:
    loop_var: rzero_config_number
