
---

#   - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ CREDENTIALS_RC_FILE }} local_dir={{ HOST_TEMP_STORAGE }} 
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_tmpl_file}}  local_dir={{ HOST_TEMP_STORAGE }}"
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_env_file}}  local_dir={{ HOST_TEMP_STORAGE }}"
#   - include: transfer_file.yaml source={{ role_path }}/files/scripts/create_heat_stack.sh  local_dir={{ HOST_TEMP_STORAGE }}
   - name: "Update Environment Variables"
     shell: "{{ HOST_TEMP_STORAGE }}/update_env_file.sh {{ HOST_TEMP_STORAGE }}  {{ heat_env_file}} {{ COMMON_ENVIRONMENT_FILENAME }}"


   - name: "Create Stack"
     shell: "{{ HOST_TEMP_STORAGE }}/create_heat_stack.sh {{ HOST_TEMP_STORAGE }}  {{heat_tmpl_file}} {{ heat_env_file}} {{ CREDENTIALS_RC_FILE | basename }}  {{VNF_IMAGE_LOCATION | basename }}"
     register: create_result
     changed_when: "create_result.rc != 2"
     failed_when: "create_result.rc == 1 or create_result.rc > 2"



#   - name: Retrieve Stack Name
#     shell: "echo {{HEAT_TEMPLATE_FILENAME}} | sed 's/\.y.*ml$/_stack/'"
#     register: stack_name

#   - name: "Retrieve Floating IP"
#     shell:  heat output-show {{stack_name}} vnfm_floating_ip
