
---

#   - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ CREDENTIALS_RC_FILE }} local_dir={{ HOST_TEMP_STORAGE }} 
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_tmpl_file}}  local_dir={{ HOST_TEMP_STORAGE }}"
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_env_file}}  local_dir={{ HOST_TEMP_STORAGE }}"

   - name: "Delete Stack"
     shell: "source {{ HOST_TEMP_STORAGE }}/{{ CREDENTIALS_RC_FILE | basename }} ;/usr/bin/openstack stack delete --yes --wait {{heat_env_file| regex_replace('^(.*).env$', '\\1') }}_stack"
     register: command_result
     failed_when: 
         - "'could not be found' not in command_result.stdout"
         - "command_result.rc != 0"
     changed_when: 
         - "'could not be found' not in command_result.stdout"
