
---

#   - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ CREDENTIALS_RC_FILE }} local_dir={{ HOST_TEMP_STORAGE }} 


   - name: "Retrieve Glance Image ID"
     shell: "source {{ HOST_TEMP_STORAGE }}/{{ CREDENTIALS_RC_FILE | basename }} ;/usr/bin/openstack image list | grep {{VNF_IMAGE_LOCATION | basename | regex_replace('^(.*).qcow2$', '\\1') }} | awk -F\"|\" '{print $2}' | head -1 | tr -d '[:space:]'"
     register: image_id
     ignore_errors: true

   - debug: var=image_id.stdout

   - name: "Delete Glance Image "
     shell: "source {{ HOST_TEMP_STORAGE }}/{{ CREDENTIALS_RC_FILE | basename }} ;/usr/bin/openstack image delete {{image_id.stdout}}" 
     register: delete_command_result
     failed_when: 
         - "'No image with an ID of' not in delete_command_result.stderr  and delete_command_result.rc !=0"
     changed_when: "'No image with an ID of' not in delete_command_result.stderr"
     when: image_id.stdout != ""

#     shell: "source {{ HOST_TEMP_STORAGE }}/{{ CREDENTIALS_RC_FILE | basename }} ;/usr/bin/glance image-list | grep {{vnf_image_name}} | awk -F\"|\" '{print $2}' | head -1 | tr -d '[:space:]'"
