---

#- hosts: localhost

#  vars: 
#    - local_dir: /home/anand/ansible_test/
#    - tmp_dir: /tmp

#  tasks:
#   - include: ./tasks/download_file.yml src_url={{ APPLICATION_LOAD_URL }} local_dir={{ LOCAL_STORAGE }}

   - name: "Getting the md5sum of remote file if it exists"
     shell: /usr/bin/md5sum {{ HOST_TEMP_STORAGE }}/{{VNF_IMAGE_LOCATION | basename }} | awk '{ print $1 }' | sed -e 's/.*No such file.*//g'
     register: md5sum_of_remotefile
     ignore_errors: true

   - debug: var=md5sum_of_remotefile.stdout

   - name: "Getting the md5sum of local file if it exists"
     local_action: shell /usr/bin/md5sum {{ source }} | awk '{ print $1 }' | sed -e 's/.*No such file.*//g'
     register: md5sum_of_localfile
     ignore_errors: true

   - debug: var=md5sum_of_localfile.stdout

   - name: "Copy file from {{ source }} to {{ local_dir }}"
     copy: src={{ source }}  dest={{ local_dir }} mode=0755 force=yes
     when: 
           md5sum_of_remotefile.stdout == ""  or
           md5sum_of_remotefile.stdout != md5sum_of_localfile.stdout
