
---

#  - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ CREDENTIALS_RC_FILE }} local_dir={{ HOST_TEMP_STORAGE }} 
#  - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ VNF_IMAGE_LOCATION }} local_dir={{ HOST_TEMP_STORAGE }} 
#  - include: transfer_image.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ VNF_IMAGE_LOCATION }} local_dir={{ HOST_TEMP_STORAGE }}
  - include: "{{ role_path }}/../common/tasks/transfer_image.yaml source={{ role_path }}/../common/{{ QCOW2_IMAGE_LOCATION }}/{{ VNF_IMAGE_LOCATION }} local_dir={{ HOST_TEMP_STORAGE }}"
#  - include: transfer_file.yaml source={{ role_path }}/files/scripts/upload_to_glance.sh  local_dir={{ HOST_TEMP_STORAGE }}

  - name: Upload image to openstack
    shell: "{{ HOST_TEMP_STORAGE }}/upload_to_glance.sh  {{ HOST_TEMP_STORAGE }} {{ CREDENTIALS_RC_FILE | basename }} {{VNF_IMAGE_LOCATION | basename }}" 
    register: upload_result
    changed_when: "upload_result.rc != 2"
    failed_when: "upload_result.rc == 1 or upload_result.rc > 2"

#    os_image:
#      name: "{{ VNF_IMAGE_LOCATION | basename | regex_replace('^(.*).qcow2$', '\\1') }}"
#      container_format: bare
#      disk_format: qcow2
#      state: present
#      filename: "{{ HOST_TEMP_STORAGE }}/{{VNF_IMAGE_LOCATION | basename }}"
