
---

#   - include: transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ CREDENTIALS_RC_FILE }} local_dir={{ HOST_TEMP_STORAGE }} 
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_tmpl_file}}  local_dir={{ HOST_TEMP_STORAGE }}"
   - include: "{{role_path}}/../common/tasks/transfer_file.yaml source={{ role_path }}/{{ HEAT_TEMPLATE_LOCATION }}/{{ heat_env_file}}  local_dir={{ HOST_TEMP_STORAGE }}"

   - name: "Validate Templates"
     shell: "source {{ HOST_TEMP_STORAGE }}/{{ CREDENTIALS_RC_FILE | basename }} ;/usr/bin/heat template-validate -f {{ HOST_TEMP_STORAGE }}/{{heat_tmpl_file}} -e {{ HOST_TEMP_STORAGE }}/{{heat_env_file}}"
     register: template_validate_command_result
     failed_when: 
         - "template_validate_command_result.rc != 0"
