---

    - include_tasks : ./Descriptor/Descriptor_Offboard_LVND_tasks.yml  LVND_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("LVND")

    - include_tasks : ./Descriptor/Descriptor_Offboard_NSD_tasks.yml   NSD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("NSD")

    - include_tasks : ./Descriptor/Descriptor_Offboard_VLD_tasks.yml   VLD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("VLD")

    - include_tasks : ./Descriptor/Descriptor_Offboard_VNFD_tasks.yml  VNFD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("VNFD")

    - include_tasks : ./Descriptor/Descriptor_Offboard_LCMD_tasks.yml  LCMD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("LCMD")


