---


    - name: Read VLD_Id attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VLD_Id }}"
         content: text
      register: xmlIDresp
      delegate_to: localhost

    - debug:
        var: "{{xmlIDresp.matches[0]['vl-id']}}"

    - name: Read NSD_Version attribute from XML
      xml:
         xmlstring: "{{lookup('file', '{{ XML_PATH }}') | regex_replace('xmlns=.*>', '>')}}"
         xpath: "{{ DESCRIPTOR_ONBOARD_CON_INFO.VLD_Version }}"
         content: text
      register: xmlVERresp
      delegate_to: localhost

    - debug:
        var: "{{xmlVERresp.matches[0]['descriptor-version']}}"

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select id from vld_descriptor where vld_id='{{xmlIDresp.matches[0][\"vl-id\"]}}' and version='{{xmlVERresp.matches[0][\"descriptor-version\"]}}'"
      when: (xmlIDresp.matches[0]["vl-id"] is defined)  and  (xmlVERresp.matches[0]["descriptor-version"] is defined)
    - set_fact: VLD_DB_Id={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - include_tasks: ../query_db.yml
      vars:
         QUERY: "select fk_nsd_descriptor from vld_descriptor where id='{{VLD_DB_Id}}'"
      when: VLD_DB_Id is defined
    - set_fact: VLD_NSD_DB_Id={{RESP.stdout_lines.0}}
      when: RESP.stdout_lines.0 is defined

    - name: Getting Access Token
      uri:
          url: "{{LOGIN_URL}}"
          method: "POST"
          body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
          status_code:  200
          body_format: json
          validate_certs: no
      register: login_response
      delegate_to: localhost

    - shell: "curl -s -k -X \"DELETE\" --cookie '{{login_response.set_cookie}}' {{DESCRIPTOR_DELETE_URL}}/VLD/{{VLD_DB_Id}}"
      delegate_to: localhost
      register: curl_resp
      when: VLD_DB_Id is defined

    - debug: msg="{{curl_resp}}"

#    - include_tasks: ../https_request.yml
#                        URL="{{DESCRIPTOR_DELETE_URL}}/VLD/{{VLD_DB_Id}}"
#                        METHOD="DELETE"
# curl -s -k -X  DELETE -F  file=@"${Depolyment_Descriptors[$Index3]}; type = text/xml" -F listName=descriptor  -F descriptorId="{{xmlIDresp.matches[0]["vl-id"]}}"  -F parentDescriptorId="{{VLD_NSD_DB_Id}}"

#      when: (VLD_NSD_DB_Id) and (xmlIDresp.matches[0]["vl-id"])
