---

    - include_tasks : ./Descriptor_Delete_LCMD_tasks.yml  LCMD_XML_PATH="{{XML_PATH}}" 
      when: XML_PATH is search("LCMD")

    - include_tasks : ./Descriptor_Delete_VNFD_tasks.yml  VNFD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("VNFD")

    - include_tasks : ./Descriptor_Delete_VLD_tasks.yml   VLD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("VLD")

    - include_tasks : ./Descriptor_Delete_LVND_tasks.yml  LVND_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("LVND")

    - include_tasks : ./Descriptor_Delete_NSD_tasks.yml   NSD_XML_PATH="{{XML_PATH}}"
      when: XML_PATH is search("NSD")
