# - include_tasks: ./ConfigModel_Add_WithYang.yml
#   when: YANG_FILE_NAME is search(".zip")
#
# - include_tasks: ./ConfigModel_Add_WithoutYang.yml
#   when: not YANG_FILE_NAME is search(".zip")

# CONFIG_MODEL_VNFD_DB_IDS
# CONFIG_MODEL_NSD_DB_IDS
#
# CONFIG_MODEL_ADD_CMDS
- name: Getting Access Token
  uri:
      url: "{{LOGIN_URL}}"
      method: "POST"
      body: '{"authType": "LOCAL", "password": "{{CMS_WEB_PASSWORD}}", "username": "{{CMS_WEB_USER}}"}'
      status_code:  200
      body_format: json
      validate_certs: no
  register: login_response
  delegate_to: localhost

- include_tasks: ./ConfigModel_Add_WithYang.yml PARAM_YANG_FILE_NAME="{{MODEL_VALUES['YANG_FILE_NAME']}}" PARAM_VDU_ID="{{MODEL_VALUES['VDU_ID']}}" PARAM_NSD_ID="{{CONFIG_MODEL_NSD_DB_IDS[MODEL_INDEX]}}" PARAM_VNFD_ID="{{CONFIG_MODEL_VNFD_DB_IDS[MODEL_INDEX]}}"
  when: MODEL_VALUES['YANG_FILE_NAME'] is search(".zip")
  loop: "{{CONFIG_MODEL_ADD_CMDS}}"
  loop_control:
    loop_var: MODEL_VALUES
    index_var: MODEL_INDEX

- include_tasks: ./ConfigModel_Add_WithoutYang.yml PARAM_YANG_FILE_NAME="{{MODEL_VALUES['YANG_FILE_NAME']}}" PARAM_VDU_ID="{{MODEL_VALUES['VDU_ID']}}" PARAM_NSD_ID="{{CONFIG_MODEL_NSD_DB_IDS[MODEL_INDEX]}}" PARAM_VNFD_ID="{{CONFIG_MODEL_VNFD_DB_IDS[MODEL_INDEX]}}"
  when: not MODEL_VALUES['YANG_FILE_NAME'] is search(".zip")
  loop: "{{CONFIG_MODEL_ADD_CMDS}}"
  loop_control:
    loop_var: MODEL_VALUES
    index_var: MODEL_INDEX
