- set_fact:
    NAME_TO_BE_USED: "{{PARAM_YANG_FILE_NAME[:30]}}-{{PARAM_VDU_ID}}"
    # FILE_ABS_PATH: "{{DESCRIPTOR_PATH}}/{{DESCRIPTOR_INFO.0}}/Yang/{{PARAM_YANG_FILE_NAME}}"
- set_fact:
    NAME_TO_BE_USED: "{{NAME_TO_BE_USED[:49]}}"

- shell: "curl -d 'listName=data_model&rowData={\"id\":\"\",\"name\":\"{{NAME_TO_BE_USED}}\",\"namespace\":\"\",\"descriptorType\":\"modelWithDescriptor\",\"dataModelType\":\"modelWithoutSchema\",\"nsdId\":\"{{PARAM_NSD_ID}}\",\"vnfdId\":\"{{PARAM_VNFD_ID}}\",\"vduId\":\"{{PARAM_VDU_ID}}\"}' --cookie '{{login_response.set_cookie}}' -H \"Content-Type: application/x-www-form-urlencoded\" -k -X POST {{DESCRIPTOR_UPLOAD_URL}}/data_model"
  register: curl_resp
  delegate_to: localhost
  # when: not RESP.stdout_lines.0 is defined

- debug: msg="{{curl_resp}}"
